README.md

Added a table with the Known Open Sourced Bots created with Discordeno.

Open Sourced Bots Table

---

module/shard.ts

This PR should address any issues with improper error code handling when the WS closes. It also helps refactor some of the code in the shard.ts file.
Closes #34

bette error handling

---

events/channels.ts

Better Error Handling

---

events/channels.ts

Add Reloadable Event Handlers To V1

---

module/shardingManager.ts
structures/message.ts

Update the `message.member` property once the full member object was created using `createMember()` function.

Add message#guild() and message#member() method to message object

---

module/shardingManager.ts
structures/message.ts
utils/cdn.ts

- fix: Message.mentions was really annoying to support and handle. The typings were being caused by an option that would never be allowed to exist anyway. Discord doesn't send users in the mentions array if its not a valid member.
- fix: Fixed the voice state bugs reported in #51
- fix: Fixed the image url formatting types. The order of operations was making it so it could never be anything but gif or jpg. This should now allow all types

Small bug fixes

---

README.md

Add a simple ping pong command example to the README, useful to have a base to start developing a bot

Add a simple ping command example to README

---

docs/content/advanced/dockerhosting.md

Added docs to help people set up Docker hosting
N/A

Added docs for setting up Docker hosting

---

.vscode/settings.json
deps.ts
src/controllers/misc.ts
src/handlers/message.ts
src/module/basicShard.ts
src/module/requestManager.ts
src/module/shard.ts
src/module/shardingManager.ts
src/utils/utils.ts

Conventionally organized dependencies

Segregate all external dependencies to deps.ts

---

deps.ts
src/module/basicShard.ts

replaced javascript implementation of zlib with webassembly

improve perf of zlib inflating

---

deps.ts
src/module/basicShard.ts

Reverts Skillz4Killz/Discordeno#124
The second parameter *limit* is required; however, it is not supplied.

Revert "improve perf of zlib inflating"

---

deps.ts
src/module/basicShard.ts

Use wasm zlib decompression instead of native zlib decompression―thanks to @devcat 
**Status**

Use wasm zlib decompression @devcat

---

deps.ts
src/module/basicShard.ts

fix zlib decompression and switch to zero-copy methods

change to zlib zero-copy inflate

---

docs/content/gettingstarted.md

This is adding another boilerplate/template to the `getting started` guide, <https://github.com/Suyashtnt/discordeno-helper-template>. It's a reimplementation of DenoBot using my framework
**Status**

Add discordeno-helper

---

src/types/activity.ts

Add "Competing" to ActivityType

---

src/types/activity.ts
src/types/discord.ts

Add missing activity types

---

src/utils/permissions.ts

Closes #144
Add an if-statement checking if channel is undefined; if it is, return false.
**Status**

Check if channel is undefined

---

src/utils/cache.ts

Remove redundant type cast

---

egg.yml
tests/mod.test.ts

@ayntee Review please and merge when ready

Fix overwrite tests

---

tests/mod.test.ts

test fix for test 14

---

deps.ts

- Update `std/encoding/base64.ts` to `0.75.0`.
- Update `std/async/delay.ts` to `0.75.0`.
- Update `@evan/wasm` to `0.0.12`.
**Status**

Update dependencies to latest

---

src/handlers/member.ts

Adds new function `moveMember(guildID: string, memberID: string, channelID: string);` to the member handler.
Closes #164
**Status**

Add moveMember function to member handler

---

docs/content/stepbystep/createbot.md

At Skillz's request, I updated the guide to reflect the new run method for mod.ts
**Status**
- [ Y] Code changes have been tested against the Discord API, or there are no code changes
- [X ] This PR changes the library's interface (methods or parameters added)
- [X ] This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
- [Y ] This PR **only** includes non-code changes, like changes to documentation, README, etc.

Update to reflect new way of running mod.ts

---

README.md

- Removes all features of the boilerplate mentioned in the README (irrelevant to **this** repository).
- Adds a link redirecting to the *Features* header in the boilerplate repository.
- Users can now add their boilerplates to the README.
Format:
```md
- Name of the boilerplate
- [GitHub](GitHub Link)
```
**Status**

Remove unnecessary clutter and features

---

src/controllers/misc.ts

Lower the time limit for ready event activation

---

src/module/requestManager.ts

Should make RequestManager way faster! This change removes the 1 second delay between processing requests that was added to prevent the max stacks error #90 Using this new tail call elimination design we can solve that error while maintaining a constant loop processing the requests.
**Status**

much faster rest

---

src/handlers/channel.ts

Add reason parameter to editChannel()

---

src/handlers/channel.ts

Added a new function isChannelSynchronized() which checks whether a channel is synchronized with its parent or not.
Closes #179 
**Status**

New function isChannelSynced(channelID: string)

---

src/controllers/cache.ts

- Added size() function the cacheHandlers.
**Status**

Add size() to cacheHandlers

---

src/constants/discord.ts
src/handlers/guild.ts
src/structures/mod.ts
src/structures/template.ts
src/types/guild.ts

- Added `Template` interface to types.
- Added seven new functions:
Reference: https://github.com/discord/discord-api-docs/pull/2144#issue-500878328
**Status**

🎉 Server Templates 🎉

---

src/module/requestManager.ts

Better error messages for request manager

---

src/handlers/channel.ts

Types for getChannelWebhooks()

---

src/handlers/guild.ts

Fixed the extra uppercase letter in the comment for unban.
I'm pretty sure it's not supposed to say "REquires"
**Status**

Fix spelling error in guild.ts

---

src/structures/role.ts
src/types/role.ts

Reference: <https://github.com/discord/discord-api-docs/issues/1537>
**Status**

Add Role.tags property

---

src/handlers/member.ts

Resolves the promise returned by urlToBase64() method.
**Status**

fix: resolve urlToBase64() promise

---

README.md

docs: add dencord-starter to the boilerplate list

---

src/controllers/guilds.ts

Fixing Bug on line 40

---

src/handlers/guild.ts

feat: better return type/value for createServer()

---

docs/package.json
docs/src/.vuepress/config.js

Repository Link was changed to discordeno/Discordeno. Also the docsDir is wrong, fixed that.
**Status**

Fix "Edit this page" Links

---

docs/src/advanced/dockerhosting.md
docs/src/faq.md
docs/src/gettingstarted.md

Since Discordeno has been moved to a github organization the Links are outdated now. Here the links are updated. Also changed some links to make them clickable.
**Status**

Update some Links

---

src/handlers/guild.ts

@ayntee requested me to do that PR.
**Status**

style: format source files

---

docs/src/.vuepress/config.js
docs/src/djs.md

Since a seperate Discord for Discordeno has been created, the invite links should be updated too.
**Status**

Update Discord Invite Links

---

README.md
docs/src/stepbystep/createevent.md

Somehow missed to update the Support Server invite link in the README.md. Don't know how I managed to miss that, have read over the file multiple times.
**Status**

Missed an Invite Link

---

src/controllers/bans.ts

fix: guildBanRemove() event not triggered

---

docs/src/stepbystep/createevent.md
src/controllers/bans.ts
src/types/options.ts

As discussed in Discord!
**Status**

Fix guild bans arg ordering

---

docs/src/stepbystep/createevent.md
src/controllers/members.ts
src/controllers/messages.ts
src/controllers/reactions.ts
src/types/guild.ts
src/types/options.ts

Skillz4Speed requested that for `guildMemberRemove` others were changed by me. I thought we could do that for everything, up to you if you are going to accept that or not.
**Status**

BREAKING: change certain events args order

---

README.md

Rename Documentation to Useful Links, since that's not all documentation. Add a link to the Documentation. Remove Contributing Guide Link since thats in the Contribution Section.
**Status**

README: Change Links and Contribution Section 

---

README.md
src/handlers/channel.ts
src/handlers/guild.ts

Since (bits, perm) => bits... is used very often and there is a function that handles that I have replaced them with the function.
Changes have not been tested right now. Still in progress.
**Status**

refactor: replace bitwise calculation with calculateBits()

---

README.md
src/handlers/channel.ts

Editing a Channel Permission is not intuitive with editChannel. editChannelOverwrite function was requested by Skillz4Killz .
Should this function take an array of objects instead of one?
**Status**

feat: add editChannelOverwrite()

---

src/types/slash.ts
src/types/types.ts
src/utils/permissions.ts

Add slash Command Types
Is this ok so?
**Status**

add: Slash Command Types 

---

src/handlers/webhook.ts
src/types/channel.ts
src/types/webhook.ts
src/utils/constants.ts

Discord has added new Webhook endpoints, here these are added.
Also adds error throw if message content is higher than 2000
**Status**

feat: New Webhook Endpoints

---

.github/workflows/lint.yml

Run CI on push, pull_request & do not run deno cache

---

src/util/constants.ts

Removed the / at the end of the constant since it's breaking all the url since the usage of this variable always add the / after the constant. ****
**Status**

Fix cdn url

---

src/interactions/README.md

docs: improve wording

---

src/interactions/deps.ts

deps: use unpkg instead of esm.sh

---

docs/package.json
docs/src/.vuepress/config.js
docs/src/.vuepress/navbar.js
docs/src/.vuepress/sidebar.js

Makes dark theme the default theme on page load :smiley: 
**Status**

docs: dark theme by default

---

src/types/channel.ts

Have checked the types against the documentation.
**Status**

fix: Channel types

---

src/types/emoji.ts

add: emoji types

---

.gitignore
.vscode/settings.json

It is quiet annoying to create this folder every time so it should be added again.
**Status**

add: vscode settings

---

src/types/emoji.ts
src/types/guild.ts

Add guild types. Imports will be added when all type files are finished.
**Status**

add: guild types

---

src/types/oauth2.ts

types: add OAuth2 type

---

src/api/handlers/channel.ts
src/util/permissions.ts

Fix permissions (sorry my ide changed & to &&)
**Status**
- [ x] Code changes have been tested against the Discord API, or there are no code changes

Fix permissions

---

src/types/interaction.ts

types: add Interactions type

---

src/types/gateway.ts

Gateway types base is finished. Still need thinking through.
**Status**

types: add Gateway types

---

src/types/audit_log.ts

types: add Audit Log types

---

src/api/handlers/channel.ts
src/api/handlers/guild.ts
src/api/handlers/message.ts
src/api/handlers/webhook.ts

docs(handlers): add jsdoc comment block

---

src/types/mod.ts

Ayntee did change the file name. I overlooked the mod.ts.
**Status**

types: fix Rate Limits export

---

src/api/controllers/interactions.ts
src/api/controllers/mod.ts
src/types/options.ts

fix: separate event for APPLICATION_COMMAND_CREATE

---

src/api/structures/channel.ts
src/api/structures/guild.ts
src/api/structures/member.ts
src/api/structures/message.ts
src/api/structures/role.ts

- Added return types for structures' method, wherever possible.
**Status**

types(structures): add return type for methods

---

src/types/message.ts

Reference: https://github.com/discord/discord-api-docs/pull/2214
**Status**

types(message): make attachment dimensions optional

---

src/types/activity.ts

Reference: https://github.com/discord/discord-api-docs/pull/2219
**Status**

types(activity): add missing properties

---

src/api/controllers/misc.ts
src/api/handlers/webhook.ts
src/types/discord.ts

fix(misc): check whether guilds' loaded every 2s

---

src/api/handlers/channel.ts
src/api/handlers/guild.ts
src/util/permissions.ts

refactor: replace "return await"

---

src/api/structures/guild.ts
src/api/structures/member.ts
src/api/structures/message.ts
src/api/types/options.ts
src/rest/mod.ts

fix(types): some bugs

---

src/api/controllers/interactions.ts

types(interaction controller): remove redundant member getting

---

src/rest/cache.ts
src/rest/queue.ts
src/rest/request.ts
src/rest/request_manager.ts
src/rest/server.ts

rest: rewrite comments

---

src/rest/cache.ts
src/rest/queue.ts
src/rest/request.ts
src/rest/request_manager.ts
src/rest/server.ts

Reverts discordeno/discordeno#359

Revert "rest: rewrite comments"

---

src/api/controllers/bans.ts
src/api/controllers/guilds.ts
src/api/controllers/interactions.ts
src/api/controllers/members.ts
src/api/controllers/messages.ts
src/api/controllers/misc.ts
src/api/controllers/reactions.ts
src/api/types/guild.ts
src/api/types/options.ts
src/api/types/voice.ts
src/bot.ts

types: update EventHandler types

---

src/api/types/gateway.ts

types: fix rename Error

---

src/api/controllers/messages.ts

remove default values in message.ts
**Status**

Types patch 1

---

mod.ts
src/api/controllers/interactions.ts
src/api/handlers/guild.ts
src/api/types/audit_log.ts
src/api/types/channel.ts
src/api/types/gateway.ts
src/api/types/guild.ts
src/api/types/invite.ts
src/api/types/permissions.ts
src/api/types/template.ts
src/api/types/user.ts
src/api/types/webhook.ts
src/types/audit_log.ts
src/types/gateway.ts
src/types/guild.ts
src/types/interaction.ts
src/types/webhook.ts

types: export all types in mod.ts

---

tests/01_main.ts
tests/05_message.ts

test(message): add missing tests

---

src/api/handlers/channel.ts
src/api/handlers/guild.ts
src/api/handlers/member.ts
src/api/handlers/message.ts
src/api/handlers/webhook.ts
src/api/structures/member.ts

types: add reason back remove unnecessary things

---

README.md
src/bot.ts
src/types/options.ts
test/mod.test.ts

feat: internal intents resolution

---

src/api/handlers/message.ts

Support for custom emojis in reaction remove functions.

fix(handlers): support for custom emoji in reaction remove functions

---

src/api/handlers/member.ts

feat(handlers): add kickFromVoiceChannel() function

---

src/api/handlers/guild.ts

feat(handlers): add editChannelOverwrite() & deleteChannelOverwrite()

---

src/api/controllers/guilds.ts

fix(controllers): cache updated guild object with new emojis

---

src/api/controllers/guilds.ts
src/api/handlers/guild.ts

Adds getEmoji functions.
Fixes emoji update event not caching emojis.
**Status**

feat(handlers): add getEmoji() & getEmojis()

---

src/api/handlers/channel.ts

feat(handlers): add startTyping()

---

src/api/handlers/member.ts

Reference: https://github.com/discord/discord-api-docs/pull/2505
**Status**

types(handlers): editMember now returns GuildMember

---

src/api/types/guild.ts
src/types/guild.ts

Reference: https://github.com/discord/discord-api-docs/pull/2509/
**Status**

types: add cover_image to IntegrationApplication Object

---

src/api/controllers/messages.ts

**Status**
code changes
README, etc.

fix(controllers): check if the cached content is same as the updated content

---

src/util/constants.ts

**Status**
code changes
README, etc.

refactor(util): remove GUILD_INTEGRATION_CREATE endpoint

---

src/api/controllers/messages.ts

**Status**
code changes
README, etc.

fix(controllers): cache updated message on MESSAGE_UPDATE

---

src/api/controllers/guilds.ts
src/api/controllers/misc.ts
src/api/structures/guild.ts
src/api/structures/member.ts
src/types/guild.ts

**Status**
code changes
README, etc.

refactor: remove index signatures

---

src/util/permissions.ts

**Status**
code changes
README, etc.

refactor(util): use getter instead

---

src/types/opcodes_status_codes.ts

Reference: https://github.com/discord/discord-api-docs/pull/2511
**Status**
code changes
README, etc.

types: add UnknownApplicationCommand error

---

src/api/controllers/guilds.ts
src/api/controllers/members.ts
src/api/controllers/misc.ts
src/api/controllers/reactions.ts
src/api/controllers/roles.ts

**Status**
code changes
README, etc.

fix(controllers): update cache with new value in gateway events

---

src/api/handlers/mod.ts

**Status**
code changes
README, etc.

fix(handlers): add missing handlers

---

src/util/cache.ts
src/ws/shard_manager.ts

types: better types

---

src/ws/shard.ts

**Status**
code changes
README, etc.

feat(ws): add additional info to wsError debug event

---

src/api/controllers/misc.ts
src/api/handlers/webhook.ts
src/bot.ts
src/util/constants.ts

Closes: https://github.com/discordeno/discordeno/issues/435
**Status**
code changes
README, etc.

fix: use applicationID for slash commands instead of botID

---

src/api/handlers/webhook.ts
src/types/webhook.ts

IMPORTANT: This PR REQUIRES #440 to be merged.
NOTE: This PR would includes breaking changes but since it is not possible that anyone has used this functions because they do not work merging this PR should be no problem.
**Status**
code changes
parameters moved or removed) (This function was never used)
README, etc.

fix(handlers): edit/upsertSlashCommand function

---

src/api/handlers/webhook.ts

**Status**
code changes
README, etc.

feat(handlers): add getSlashCommand()

---

src/api/types/gateway.ts
src/types/gateway.ts

Only adds types. Waiting for ayntees PR to add the events. Master branch then gets merged into types.
**Status**
code changes
README, etc.

add(types): integration types

---

src/util/permissions.ts

**Status**
code changes
README, etc.

fix(util): use custom cache instead of default cache

---

src/util/utils.ts
test/util/utils.test.ts

**Status**
code changes
README, etc.

feat(util): add camelToSnakeCase() & snakeToCamelCase()

---

src/api/handlers/channel.ts
src/api/handlers/gateway.ts
src/api/handlers/guild.ts
src/api/handlers/member.ts
src/api/handlers/message.ts
src/api/handlers/oauth.ts
src/api/handlers/webhook.ts

Closes: #465
**Status**
code changes
README, etc.

refactor(handlers):  resolve RequestManager.<method> using await before returning the value

---

src/api/handlers/channel.ts

**Status**
code changes
README, etc.

Attempt to fix CI

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
.github/workflows/test.yml

**Status**
code changes
README, etc.

ci: add matrix testing

---

test/mod.test.ts

**Status**
code changes
README, etc.

test: await all handlers

---

.github/workflows/lint.yml
src/api/controllers/misc.ts
src/api/controllers/mod.ts
src/types/discord.ts
src/types/guild.ts
src/types/message.ts
src/types/options.ts
src/types/util.ts

Closes: #457 
Reference: https://github.com/discord/discord-api-docs/pull/2533

feat(controllers): add INTEGRATION* gateway events

---

src/api/controllers/interactions.ts
src/api/controllers/mod.ts
src/types/discord.ts
src/types/interactions.ts
src/types/options.ts

Reference: https://github.com/discord/discord-api-docs/pull/2367/

feat(controllers/interactions): add APPLICATION_COMMAND_{CREATE,UPDATE,DELETE} events

---

src/util/permissions.ts

fix(util/permissions): include guild ID while resolving bits

---

src/rest/request_manager.ts
src/types/channel.ts

feat(rest/request_manager): support for multiple attachments

---

src/rest/request_manager.ts
src/types/channel.ts

Reverts discordeno/discordeno#484

Revert "feat(rest/request_manager): support for multiple attachments"

---

src/api/controllers/misc.ts
src/api/controllers/mod.ts
src/types/discord.ts
src/types/options.ts

feat(controllers/misc): add inviteCreate & inviteDelete listeners

---

src/bot.ts

fix(bot): fix skipChecks logic

---

src/api/controllers/guilds.ts

fix(controllers/guild): guildDelete listener not emitted & guildUpdate listener caching irrelevant fields

---

src/ws/shard.ts

feat(ws/shard): add sendWS()

---

src/api/controllers/channels.ts
src/api/controllers/guilds.ts
src/api/controllers/interactions.ts
src/api/controllers/members.ts
src/api/controllers/messages.ts
src/api/controllers/misc.ts
src/api/controllers/reactions.ts
src/api/handlers/guild.ts
src/api/handlers/member.ts
src/api/structures/channel.ts
src/api/structures/guild.ts
src/api/structures/member.ts

fix: remove structure automatic caching

---

src/api/structures/message.ts

feat(structures/message): add DM redirect for send message methods

---

src/api/structures/channel.ts
src/api/structures/guild.ts

feat(structures/channel): add getters and handlers to Channel struct

---

src/ws/shard.ts

feat(ws/shard): add closeWS() function

---

src/rest/queue.ts

fix(rest/queue): logical error in response status handling

---

src/util/permissions.ts

fix(util/permissions): move owner check before member cache check

---

src/api/structures/member.ts

docs(structures/member): update description for Member#guildMember()

---

src/types/api/auditlog.ts

feat(types/auditlog): add missing props to DiscordAuditLogChange interface

---

.github/workflows/lint.yml
src/interactions/types/interactions.ts

fix(types/interactions): make "content" optional in SlashCommandCallbackData

---

src/api/handlers/message.ts

feat(handlers/message): add options to getReactions

---

src/types/api/embed.ts
src/types/message.ts

feat(types/embed): add proxy_url to EmbedVideo interface

---

src/api/handlers/webhook.ts
src/types/webhook.ts

fix(handlers/webhook): update slash commands handlers' types

---

src/interactions/types/interactions.ts
src/types/webhook.ts

fix(types/webhook): update interaction response types

---

src/types/api/interaction.ts
src/types/api/member.ts

feat(types/interaction): add "resolved" field to DiscordInteractionCommand

---

src/api/handlers/guild.ts
src/types/guild.ts

Reference: https://discord.com/developers/docs/resources/guild#begin-guild-prune

feat(types/guild): add computePruneCount to PruneOptions

---

src/interactions/types/interactions.ts
src/types/webhook.ts

Reverts discordeno/discordeno#610

Revert "fix(types/webhook): update interaction response types"

---

src/api/handlers/webhook.ts

Reverts discordeno/discordeno#611

Revert "fix(handlers/webhook): return Message object instead of raw payload"

---

src/interactions/types/member.ts
src/types/member.ts

feat(types/member): add permissions in MemberCreatePayload

---

src/api/handlers/channel.ts
src/api/structures/message.ts
src/types/channel.ts
src/types/message.ts

Alternative to #596 
Closes #581

feat(types/message): add fail_if_not_exists to Reference interface

---

src/types/api/interaction.ts

Reference:  https://github.com/discord/discord-api-docs/pull/2684

feat(types/interaction): add missing fields in DiscordInteractionDataOption

---

src/api/handlers/channel.ts

fix(handlers/channel): add permission handler for startTyping()

---

src/api/handlers/member.ts

fix(handlers/member): change editMember() to return a Member object

---

src/types/interactions.ts

fix(types/interactions): remove "default" from ApplicationCommandOption

---

src/api/handlers/guild.ts
test/mod.test.ts

feat(handlers/guild): change createGuildChannel() to use guild ID

---

src/api/handlers/webhook.ts

Reverts discordeno/discordeno#634

fix(handlers/webhook): return Message object instead of raw payload

---

src/api/handlers/channel.ts
src/api/structures/channel.ts
src/types/channel.ts

refactor: rename slowmode to rateLimitPerUser

---

src/api/handlers/guild.ts
src/types/guild.ts

refactor(handlers/guild): rename roles option to includeRoles

---

src/api/controllers/CHANNEL_PINS_UPDATE.ts
src/api/controllers/channels.ts
src/api/controllers/mod.ts
src/types/discord.ts
src/types/options.ts

feat(controllers): add CHANNEL_PINS_UPDATE controller

---

src/api/controllers/GUILD_INTEGRATIONS_UPDATE.ts
src/api/controllers/guilds.ts
src/api/controllers/mod.ts
src/types/discord.ts
src/types/options.ts

feat(controllers): add GUILD_INTEGRATIONS_UPDATE controller

---

src/helpers/message.ts

refactor(helpers/message): divide message arg into channelID & messageID in getReactions()

---

src/helpers/members/fetch_members.ts
src/helpers/members/get_members_by_query.ts
src/ws/shard_manager.ts

refactor: use guildID and shardID as args in requestAllMembers() & fetchMembers()

---

src/helpers/commands/send_interaction_response.ts
src/helpers/mod.ts
src/interactions/types/slash.ts
src/types/webhook.ts

refactor(helpers): rename executeSlashCommand to sendInteractionResponse

---

src/util/collection.ts

fix(util/collection): .first(), .last(), .random() may return undefined

---

src/util/collection.ts
src/util/utils.ts

refactor(util): remove chooseRandom()

---

src/types/util.ts

types(util): recursive CamelCaseProps and SnakeCaseProps

---

src/types/oauth2/application.ts
src/types/oauth2/bot_auth_query.ts
src/types/oauth2/get_current_authorization_information.ts
src/types/oauth2/scopes.ts

The `Application` type is needed for the `Ready` type.

types: add oauth2 types

---

src/rest/mod.ts

request_manager.ts was removed in #732

fix(rest): remove export of request_manager

---

src/helpers/guilds/guild_banner_url.ts
src/helpers/guilds/guild_icon_url.ts
src/helpers/guilds/guild_splash_url.ts
src/helpers/members/avatar_url.ts
src/structures/guild.ts
src/util/utils.ts

Guild functions remove cache requirement

---

mod.ts
src/util/random.ts

I don't personally think this should be removed, but if you guys feel it should be feel free to merge this pr

chore: removes random util

---

src/structures/role.ts

Fixed:
- type changes
- MemberStructure
Added:
- guildId
- higherThanMember

fix(structures/role): use new types & add MemberStruct interface

---

.github/workflows/coverage.yml
README.md

You just need to sign up on codecov https://codecov.io/
This should add denos coverage feature.
Closes: #791

add(github/workflows): test coverage

---

.github/workflows/coverage.yml

I will never copy paste again.

fix(github/workflows): coverage wrong test command

---

.github/CODEOWNERS
.github/workflows/test.yml

Sad to say but as long as ayntee does not have perms on discordeno having him in these files does not work.

remove ayntee from .github

---

src/rest/process_request_headers.ts

It is possible that a computers clock goes ahead so we should use the `retry-after` header to calculate the resetTimestamp instead.

fix(rest): processRequestHeaders proper resetTimestamp

---

.github/workflows/lint.yml

Not tested though.
Closes #792

ci(lint): "auto-format" the files and push the changes

---

src/helpers/misc/edit_bot_status.ts
src/ws/heartbeat.ts
src/ws/identify.ts
src/ws/process_queue.ts
src/ws/resume.ts
src/ws/ws.ts
tests/ws/start_bot.ts

feat: implement gateway queue

---

src/helpers/channels/get_channel_webhooks.ts
src/helpers/channels/get_channels.ts
src/helpers/emojis/get_emojis.ts
src/helpers/invites/get_channel_invites.ts
src/helpers/invites/get_invites.ts
src/helpers/roles/get_roles.ts
src/helpers/templates/get_guild_templates.ts
src/helpers/webhooks/get_webhooks.ts

fix: return types [] => Collection

---

src/helpers/guilds/update_bot_voice_state.ts
src/helpers/guilds/update_user_voice_state.ts
src/types/channels/channel_types.ts
src/types/guilds/update_others_voice_state.ts
src/types/guilds/update_self_voice_state.ts
src/types/permissions/bitwise_permission_flags.ts
src/types/voice/voice_state.ts
src/util/constants.ts

Ref: https://github.com/discord/discord-api-docs/pull/2751

feat: add support for stage channels

---

src/ws/identify.ts
src/ws/process_queue.ts
src/ws/resume.ts
src/ws/spawn_shards.ts
src/ws/ws.ts

- `queueMinuteTimestamp` so counter gets reset after every minute

fix some ws things (better title later when I found and finished fixing stuff)

---

src/ws/close_ws.ts
src/ws/handle_on_message.ts
src/ws/heartbeat.ts
src/ws/identify.ts
src/ws/resume.ts
src/ws/spawn_shards.ts
src/ws/tell_cluster_to_identify.ts
src/ws/ws.ts
tests/ws/ws_close.ts

- The first heartbeat should not wait for the entire interval to pass so changed to use setTimeout
- InvalidSession resuming/reidentifying should wait a random amount of time
- reidentify if sessionId is undefined 
- terminate connection if discord did not ACK in time
Skillz is this good? Tbh I'm not 100% sure.

fix some ws things

---

src/helpers/commands/batch_edit_slash_command_permissions.ts
src/helpers/commands/create_slash_command.ts
src/helpers/commands/edit_slash_command_permissions.ts
src/helpers/commands/get_slash_command_permission.ts
src/helpers/commands/get_slash_command_permissions.ts
src/helpers/mod.ts
src/util/constants.ts

Application command permissions

---

src/types/invites/invite.ts

Reference: https://github.com/discord/discord-api-docs/commit/6dc1b2a3e7aad5145420f965e3ec15f3b7ed7074

feat(types): add expiresAt field to Invite interface

---

src/types/webhooks/edit_webhook_message.ts

Reference: https://github.com/discord/discord-api-docs/commit/5afbad75892a907726ab47eea4d9bcbeabcdaa18

feat(types): add attachments field to EditWebhookMessage

---

src/types/messages/edit_message.ts

Reference: https://github.com/discord/discord-api-docs/commit/0b2b84d94b9abd4688158edf0534dfdd062591b4

add(types): attachments field to EditMessage

---

src/types/interactions/application_command_option_types.ts

Reference: https://github.com/discord/discord-api-docs/commit/91379ed78710d3020dcb46521485abecdf31e1d0

add(types): MENTIONABLE to DiscordApplicationCommandOptionTypes

---

src/types/invites/get_invite.ts

Reference: https://github.com/discord/discord-api-docs/commit/2c9f17887a8e5c95d48b93901f4543beda4c09be

add(types): withExpiration field to GetInvite

---

src/types/codes/json_error_codes.ts

Reference: https://github.com/discord/discord-api-docs/commit/77c375643616246f23a84e5f63d9cf9776e9a164

add(types): maximum non guild members ban error code

---

src/types/guilds/guild.ts

Reference: https://github.com/discord/discord-api-docs/commit/5e63e309bbc7e93b683b47bc8401d2d079580251

add(types): nsfw field

---

src/structures/message.ts
src/types/messages/message.ts

Reference: https://github.com/discord/discord-api-docs/pull/2908

add(structures): applicationId to Message

---

src/helpers/channels/threads/start_thread.ts
src/helpers/members/prune_members.ts
src/types/teams/team.ts

Reference: https://github.com/discord/discord-api-docs/pull/2900

add: team name param

---

src/helpers/channels/threads/start_thread.ts
src/helpers/members/prune_members.ts
src/types/interactions/commands/application_command.ts
src/types/interactions/commands/application_command_option.ts
src/types/interactions/commands/create_global_application_command.ts
src/types/interactions/commands/create_guild_application_command.ts
src/types/interactions/commands/edit_global_application_command.ts
src/types/interactions/commands/edit_guild_application_command.ts
src/util/utils.ts

Reference: https://github.com/discord/discord-api-docs/pull/2901

change: command names can only be lowercase

---

src/handlers/misc/READY.ts

fix: lastShardId instead of maxShards

---

src/types/members/guild_member_update.ts

Reference: https://github.com/discord/discord-api-docs/pull/2911

fix(types): joinedAt is nullable

---

src/types/users/user_flags.ts

Reference: https://github.com/discord/discord-api-docs/pull/2946

add(types): DiscordCertifiedModerator to user flags enum

---

src/helpers/channels/clone_channel.ts
src/types/guilds/create_guild_channel.ts
tests/channels/category_children.ts
tests/channels/is_channel_synced.ts

change: CreateChannelOptions.parentId should use bigint

---

src/types/webhooks/create_webhook.ts

fix: CreateWebhook.avatar is optional

---

.github/workflows/pr_tests.yml
.github/workflows/test.yml
README.md

Temporarily removing coverage report until it is a stable feature

remove: coverage report

---

.gitignore
src/types/guilds/guild.ts
src/types/guilds/guild_nsfw_level.ts

Reference: https://github.com/discord/discord-api-docs/pull/2976

add(types): nsfw_level field to Guild

---

src/helpers/invites/create_invite.ts
src/helpers/invites/delete_invite.ts
src/helpers/invites/get_channel_invites.ts
src/helpers/invites/get_invite.ts
src/helpers/invites/get_invites.ts

fix: invite helper types

---

src/helpers/members/edit_member.ts

fix: always false if check for editMember voice

---

src/handlers/misc/USER_UPDATE.ts
src/structures/member.ts
src/structures/message.ts

fix user update

---

src/handlers/misc/USER_UPDATE.ts
src/helpers/members/avatar_url.ts
src/structures/member.ts

change: member.discriminator from bigint to number

---

src/structures/channel.ts
src/structures/guild.ts
src/structures/member.ts
src/structures/message.ts
src/structures/role.ts
src/structures/voice_state.ts

change: structure loops use Object.keys

---

src/types/applications/application.ts

Reference: https://github.com/discord/discord-api-docs/pull/3046

fix: Application#owner is optional

---

src/types/codes/json_error_codes.ts

Reference: https://github.com/discord/discord-api-docs/pull/3070

add: JSON Error Code 20031

---

src/handlers/voice/VOICE_STATE_UPDATE.ts
src/types/discordeno/event_handlers.ts
src/types/voice/voice_state.ts

Reverts discordeno/discordeno#995
Ref: https://github.com/discord/discord-api-docs/pull/2994

fix: VoiceState#member is not nullable

---

src/types/audit_log/audit_log_change.ts
src/types/audit_log/audit_log_events.ts
src/types/audit_log/optional_audit_entry_info.ts

Reference: https://github.com/discord/discord-api-docs/pull/3060

add: audit log types for stage instances

---

src/types/guilds/guild_features.ts

Reference: https://github.com/discord/discord-api-docs/pull/3059

add: Ticket, Monetization, Stickers guild features

---

src/types/interactions/commands/application_command.ts

Reference: https://github.com/discord/discord-api-docs/pull/3069

add: ApplicationCommand#guildId

---

src/types/codes/json_error_codes.ts

Reference: https://github.com/discord/discord-api-docs/pull/3108

feat(types): add 16000{4,5,6,7} to DiscordJsonErrorCodes

---

src/types/invites/invite.ts
src/types/invites/invite_stage_instance.ts
src/ws/start_gateway.ts

Reference: https://github.com/discord/discord-api-docs/pull/3120

feat(types): add stageInstance field to Invite

---

src/types/channels/channel.ts

Reference: https://github.com/discord/discord-api-docs/pull/3108﻿

feat(types): add defaultAutoArchiveDuration field to Channel

---

src/handlers/channels/THREAD_MEMBER_UPDATE.ts

docs(handlers): fix typo

---

src/helpers/misc/edit_bot_profile.ts

null shall be passed to reset the bots avatar

fix: botAvatarURL is nullable

---

src/types/messages/message_sticker.ts

Reference: https://github.com/discord/discord-api-docs/commit/9c3577f6ca35904462adf8d57c4346afd2a6bcf0﻿

feat(types): add available, guildId, user, sortValue to MessageSticker

---

src/helpers/mod.ts
src/helpers/oauth/get_application.ts

Add a helper method to retrieve the application info. Seems it was removed - old PR was #428

feat: helper method to retrieve application info

---

src/types/messages/message.ts
src/types/messages/message_sticker_item.ts

Reference: https://github.com/discord/discord-api-docs/pull/3171

add: stickerItems field to Message

---

src/types/codes/json_error_codes.ts

Reference: https://github.com/discord/discord-api-docs/pull/3193

feat(types): add 10068 code to DiscordJsonErrorCodes

---

src/cache.ts

add(structures): cache.requiredStructureProperties.members guilds prop to type

---

src/helpers/members/edit_member.ts

fix(helpers): pass null if options.channelId is falsy

---

src/types/interactions/commands/edit_global_application_command.ts

types: add defaultPermission field to EditGlobalApplicationCommand

---

src/types/channels/channel.ts
src/types/interactions/commands/application_command_interaction_data_resolved.ts

fix(types): interaction resovled data channel permission prop

---

tests/local.ts
tests/util/validateLength.ts

Pretty much copied from current dd. Closes #1366

✨ feat: unit test - utils - validateLength

---

tests/local.ts
tests/util/hasProperty.ts

Unit test / Util / hasProperty

---

tests/local.ts
tests/util/hash.ts

Unit Test Utils: iconHashToBigInt iconBigIntToHash

---

src/transformers/interaction.ts

The data field is missing in the interaction transformer.
I just passed the data field but it should be converted to camel case.
Not sure on how to handle it exactly because there is 4 different types of data.

Fix: Add missing interaction data

---

tests/helpers/messages/getMessage.ts
tests/mod.ts

[Unit Test] messages: getMessage

---

src/cache.ts

We need to think about how to implement cache.members in a good way.
It will currently not work correctly.
This at least make it possible to get users being cached.

Fix cache: implement GUILD_MEMBER_CHUNK

---

tests/helpers/members/ban.ts
tests/mod.ts

Made the tests for ban (With and Without reason), unban and getBans

feat(tests): added getBans, unban, ban

---

tests/local.ts
tests/util/permissions.ts
tests/util/utils.ts

- add unitTest/util/calculateBits
- rework unitTest/util/delay

add unitTest/util/calculateBits and rework unitTest/util/delay

---

src/bot.ts

return customUrl on rest

---

src/types/codes/jsonErrorCodes.ts

add(JsonErrorCodes): code 50101

---

src/helpers/oauth/getApplicationInfo.ts

change(getApplicationInfo): returns Application with flags

---

src/types/channels/threads/startThread.ts

feat(types): add rateLimitPerUser to StartThreadBase

---

src/handlers/mod.ts
src/helpers/mod.ts

import {} from ""
export {}
=>
export * from ""

(import -> export) => export * from

---

src/types/codes/jsonErrorCodes.ts

add(types): JsonErrorCodes::MaximumNumberOfUncompletedGuildScheduledEventsReached

---

tests/constants.ts
tests/members/getMembers.ts
tests/mod.ts

getMembers test

---

tests/members/editBotNickname.ts
tests/mod.ts

UNIT TEST editBotNickname

---

.github/workflows/pr_tests.yml

Close #1823

---

src/helpers/misc/editBotStatus.ts
tests/members/editBotNickname.ts
tests/misc/editBotStatus.ts
tests/mod.ts

UNIT TEST editBotStatus

---

README.md

fix incompatible version in minimal example in README

---

src/types/invites/invite.ts

Convert Invite#channel to a nullable property

---

src/transformers/guild.ts
src/types/guilds/guild.ts
src/types/guilds/modifyGuild.ts

Add {Guild,ModifyGuild}#premiumProgressBarEnabled

---

src/types/codes/jsonErrorCodes.ts

Add 50109 error code to JsonErrorCodes enum

---

src/types/codes/gatewayCloseEventCodes.ts
src/types/codes/gatewayOpcodes.ts
src/types/codes/httpResponseCodes.ts
src/types/codes/jsonErrorCodes.ts
src/types/codes/rpcCloseEventCodes.ts
src/types/codes/rpcErrorCodes.ts
src/types/codes/voiceCloseEventCodes.ts
src/types/codes/voiceOpcodes.ts

Copy opcodes and status codes description|explanation|meaning and paste to jsdoc comments

---

src/helpers/guilds/guildIconUrl.ts
src/helpers/guilds/guildSplashUrl.ts
src/helpers/members/avatarUrl.ts
src/helpers/misc/editBotProfile.ts

if all the properties in it is optional then why is it required

make some function params optional

---

src/types/messages/message.ts

#1858 Tweak application_id wording on message object

Tweak application_id wording on message object

---

src/bot.ts
src/helpers/channels/createStageInstance.ts
src/helpers/channels/getStageInstance.ts
src/helpers/channels/updateStageInstance.ts
src/transformers/stageInstance.ts

add transformStageInstance transformer
add transformStageInstance transformer to bot.transformers
updateStageInstance, createStageInstance, getStageInstance use transformStageInstance transformer

updateStageInstance, createStageInstance, getStageInstance should use a transformer

---

src/types/guilds/modifyGuildMember.ts
src/types/members/guildMember.ts
src/types/members/guildMemberUpdate.ts
src/types/permissions/bitwisePermissionFlags.ts

#1857 
update ModifyGuildMember, GuildMember, and GuildMemberUpdate interfaces
update BitwisePermissionFlags enum

Document Guild Member Timeout

---

src/helpers/guilds/scheduledEvents/createScheduledEvent.ts
src/helpers/guilds/scheduledEvents/editScheduledEvent.ts
src/types/guilds/scheduledEvents.ts

#1848 
add reason to CreateScheduledEvent and EditScheduledEvent interfaces
add reason.options.reason to bot.rest.runMethod's body parameter in createSheduledEvent and editSheduledEvent functions

Document audit logs for scheduled events

---

src/helpers/guilds/getAuditLogs.ts
src/types/auditLog/auditLog.ts

guild_scheduled_events not scheduled_events bruh
(new pr because I accidentally closes #1873)

fix get audit logs test

---

src/helpers/guilds/scheduledEvents/getScheduledEventUsers.ts
src/types/guilds/scheduledEvents.ts

Document max value for GET event users limit param

---

src/transformers/member.ts
src/types/members/guildMember.ts

Date.parse member.communicationDisabledUntil

---

src/types/auditLog/auditLogChange.ts

discord/discord-api-docs@1283c44
Closes: #1898

discord-api-docs: Document thread invitable audit log change key

---

src/helpers/emojis/createEmoji.ts
src/helpers/emojis/editEmoji.ts

Parse createEmoji and editEmoji bigint to string

---

src/transformers/interaction.ts
src/types/interactions/commands/applicationCommandInteractionDataResolved.ts
src/types/interactions/commands/applicationCommandOptionTypes.ts

feat: attachment option

---

src/types/codes/jsonErrorCodes.ts

discord/discord-api-docs@a833b5c
Closes: #1902

discord-api-docs: Error code 50086

---

src/transformers/channel.ts
src/types/channels/channel.ts

discord/discord-api-docs@13e45f4
Closes: #1904

discord-api-docs: Clarification on channel icons

---

src/transformers/channel.ts
src/types/channels/channel.ts
src/types/channels/threads/threadMetadata.ts

discord/discord-api-docs@53ee010
Closes: #1911

discord-api-docs: Document thread.create_timestamp

---

src/types/codes/jsonErrorCodes.ts

discord/discord-api-docs@1be6065
Closes: #1914

discord-api-docs: Adds error 50068

---

.github/CONTRIBUTING.md

Types have to be done in a different PR by skillz.
Closes: #1884

chore(.github): update contributing guidelines

---

src/bot.ts
src/handlers/channels/STAGE_INSTANCE_CREATE.ts
src/handlers/channels/STAGE_INSTANCE_DELETE.ts
src/handlers/channels/STAGE_INSTANCE_UPDATE.ts
src/helpers/channels/createStageInstance.ts
src/transformers/guild.ts
src/transformers/stageInstance.ts
src/types/channels/privacyLevel.ts
src/types/channels/stageInstance.ts

discord/discord-api-docs@8b2b155
Closes: #1903

discord-api-docs: Document stage discovery as deprecated

---

src/bot.ts
src/helpers/guilds/getGuildPreview.ts
src/transformers/mod.ts
src/transformers/sticker.ts
src/types/guilds/guildPreview.ts

discord/discord-api-docs@5b023e0
Closes: #1901

discord-api-docs: Add stickers on preview

---

site/docusaurus.config.js
site/src/components/HomepageFeatures.tsx

fix: docs home page

---

src/transformers/scheduledEvent.ts
src/types/guilds/scheduledEvents.ts

discord/discord-api-docs@dfb7310
Closes: #1936

discord-api-docs: Document Scheduled Event Covers

---

.github/workflows/npm.yml
dnt.ts

This action is based on: https://github.com/denoland/dnt#github-actions---npm-publish-on-tag
Note for @Skillz4Killz don't forget to set the npm token secret.

ci(npm): publish to npm on tag creation

---

src/bot.ts
src/rest/createRequestBody.ts
src/ws/identify.ts
src/ws/resharder.ts
src/ws/resume.ts

refactor!: do not store token prefixed with `Bot`

---

src/types/messages/components/inputTextComponent.ts

This PR adds support for the Pre-Filled value for `InputTextComponent`s

feat(types): add `value` to `InputTextComponent`

---

plugins/permissions/src/guilds/welcomeScreen.ts

Closes: https://github.com/discordeno/discordeno/issues/1973

fix(plugins/permissions): getting disabled welcome screens requires `MANAGE_GUILD` 

---

helpers/guilds/getAuditLogs.ts
transformers/auditlogEntry.ts
types/auditLog/auditLog.ts
types/auditLog/auditLogChange.ts

Closes: #1891 
Reference: <https://discord.com/developers/docs/resources/audit-log#audit-log-entry-object-audit-log-change-key>

Fix bug in audit log transformer and helper

---

types/permissions/bitwisePermissionFlags.ts

Closes: #1974 
Upstream: https://github.com/discord/discord-api-docs/commit/95994a96f18bc98e5a69c15308a78d9029b5319b

docs(types): Clarify documentation on the `CREATE_PUBLIC_THREADS` permission

---

template/beginner/bot.ts

I have adjusted the path to src so that you can start the bot directly already now

edit Command path

---

plugins/permissions/src/channels/stage.ts

There is one more type error [here](https://deno.land/x/discordeno@13.0.0-rc20/plugins/permissions/src/webhooks/editWebhook.ts), but I am not sure how to fix that one.

🐛 fix: perms plugin  - stage type error

---

types/interactions/commands/applicationCommandCallbackData.ts

Closes: #1916
Upstream: https://github.com/discord/discord-api-docs/commit/1d39b02ca8dcc54d33316cc95e6eccfb8c7725cc

docs(types): clarify which message flags can be sent

---

site/docs/big-bot-guide/gateway.md
site/docs/nodejs/Structures/create-structure.md

Just some small bugs with big bot guide's gateway and nodejs structure docs, it should be good now I guess

fix: bugs in docs

---

handlers/guilds/GUILD_CREATE.ts
handlers/guilds/GUILD_LOADED_DD.ts
handlers/guilds/GUILD_UPDATE.ts
helpers/guilds/scheduledEvents/getScheduledEventUsers.ts
plugins/cache/src/dispatchRequirements.ts
plugins/cache/src/setupCacheRemovals.ts
transformers/guild.ts
transformers/interaction.ts
types/shared.ts
util/collection.ts

fix: get rid of type errors for now

---

.github/workflows/local_tests.yml
.github/workflows/test.yml

This PR will break tests!!
As long as the templates are not fixed on the main branch.

ci: cache template code

---

helpers/interactions/sendInteractionResponse.ts

Add value for textinput

---

helpers/channels/createChannel.ts

Closes: #2166 
Upstream: https://github.com/discord/discord-api-docs/commit/032dec6c5680c9c249f3ab403c920e5cbb2d9b50

Add default_auto_archive_duration to createChannel helper options

---

util/collection.ts

Ignores maxSize
```js
collection.set('292892', {name: 'test'}, {forceSet: true})
```

Add forceSet option for collection

---

types/discord.ts

close #2250 
upstream https://github.com/discord/discord-api-docs/commit/317141784b228c37d00cb15219a490817065afe4

Clarify that permissions can apply on application-level

---

bot.ts
transformers/mod.ts
transformers/reverse/activity.ts
transformers/reverse/application.ts
transformers/reverse/member.ts
transformers/reverse/mod.ts
transformers/reverse/team.ts

This PR adds some more reverse transformers (user, member, team, activity, application) as suggested in #1885, I can work on adding other reverse transformers if the PR merged

feat: reverse transformers

---

helpers/members/fetchMembers.ts

PR has been tested and will be merged

Simplify fetchMembers

---

helpers/roles/editRole.ts

**Changes have been tested**
Code is identical to createRole

Add Role Icon to Edit

---

helpers/interactions/commands/createApplicationCommand.ts
transformers/applicationCommandOption.ts
types/discord.ts

Changes have been tested
Code identical to min value & max value

Add mix max length

---

helpers/messages/sendMessage.ts
helpers/webhooks/editWebhookMessage.ts
types/discordeno.ts

Fix Disabled Options

---

transformers/interaction.ts
types/discord.ts

Changes have been tested
Small changes

Add app_permissions

---

util/routes.ts

thread_id instead of threadId

---

helpers/interactions/sendInteractionResponse.ts

feat: Create `ApplicationCommandFlags` enumerator.

---

helpers/channels/editChannel.ts
plugins/permissions/src/channels/createChannel.ts
plugins/permissions/src/channels/mod.ts
types/discord.ts
types/shared.ts

closes #2410 
upstream https://github.com/discord/discord-api-docs/commit/77473c89983a88f1c3039860add9fb2f20208331

update forum channel type

---

bot.ts
helpers/interactions/commands/editInteractionResponse.ts
helpers/interactions/followups/editFollowupMessage.ts
helpers/messages/editMessage.ts
helpers/webhooks/editWebhookMessage.ts
plugins/permissions/src/attachments.ts
plugins/permissions/src/interactions/commands.ts
plugins/permissions/src/interactions/editFollowupMessage.ts
plugins/permissions/src/messages/create.ts
plugins/permissions/src/webhooks/message.ts
transformers/attachment.ts
transformers/reverse/attachment.ts
types/discord.ts

close #2403 
upstream https://github.com/discord/discord-api-docs/commit/7f5cbe3be42372a1f5655f717a41cf64f7a2ff62

add limit for attachment description

---

transformers/integration.ts
types/discord.ts

closes #2406 
upstream https://github.com/discord/discord-api-docs/commit/03ba219d490701352ed1d5b9307b8199e458641c

Add scopes field to integration structure

---

README.md

- Changed the dependency import to match final version
- Turn the type value of `Deno.env.get("BOT_ID")` into bigint (I am unsure if this is necessary)

Updated example code to match final version

---

rest/runMethod.ts
rest/sendRequest.ts

Reverts the change of my first fix and takes another approach.
**Please review this properly**

Fix Internal Proxy Error

---

template/.gitignore
template/nodejs/Managers/CommandManager.js
template/nodejs/Managers/EventManager.js
template/nodejs/Plugins/General/commands/ping.js
template/nodejs/Structures/BaseCommand.js
template/nodejs/events/ready.js
template/nodejs/index.js

Fix nodejs guide

---

helpers/messages/sendMessage.ts
transformers/message.ts

Closes: #2455 
Upstream: https://github.com/discord/discord-api-docs/commit/62fb60ced0f514414004d4a73b00b1aaa869b20b

add nonce to sendMessage options

---

types/discord.ts

Closes: #2457 
Upstream: https://github.com/discord/discord-api-docs/commit/ed87ef81687747da13f26da68b618a326aa039bf
Closes: #2456 
Upstream: https://github.com/discord/discord-api-docs/commit/922f789e861d0f1e5d682b5c04950856001c1bf1

add union type DiscordConnectionServices

---

helpers/guilds/invites/createInvite.ts

fix: createInvite doesnt pass reason

---

helpers/interactions/responses/editFollowupMessage.ts
helpers/interactions/responses/editOriginalInteractionResponse.ts
helpers/webhooks/editOriginalWebhookMessage.ts
helpers/webhooks/editWebhookMessage.ts

fix(helpers): edit interaction responses & webhook messages does not update files

---

site/docs/big-bot-guide/cache.md
site/docs/big-bot-guide/events.md
site/docs/big-bot-guide/gateway.md
site/docs/big-bot-guide/rest.md
site/docs/big-bot-guide/step-by-step.md

This PR updates big bot guide to dd v16, fixes bugs with cache in `events.md` (cache property no longer exists), added missing code for handling incoming gateway events in `events.md`

docs(big-bot-guide): Updated to dd v16, fixed bugs, added missing code

---

site/docs/general/frequently-asked-questions.md
site/docs/general/getting-started.md
site/docs/general/migrating.md

docs(general): fix code to work with v16

---

transformers/toggles/guild.ts
types/shared.ts

Please review the bitshifting.

feat(transformers,types): add DEVELOPER_SUPPORT_SERVER feature (fixes #2550)

---

site/docs/amethyst/AmethystEmbed.md
site/docs/amethyst/_category_.json
site/docs/amethyst/exampleBot.md

The doc now uses the latest Amethyst Update.

feat(Amethyst): Update Docs

---

.github/workflows/benchmark.yml
performance/generateMessage.ts
performance/mod.ts
performance/tranformOutput.ts

This PR adds a result multiplier using sysbench cpu event per second. This should hopefully reduce the deviation created by github action running on different cpu. Also add some more bench

bench: add cpu correction

---

.vscode/settings.json
debug.rest.ts
gateway/shard/connect.ts
gateway/shard/types.ts
rest/cleanupQueues.ts
rest/createInvalidRequestBucket.ts
rest/createQueueBucket.ts
rest/processGlobalQueue.ts
rest/processQueue.ts
rest/processRequest.ts
rest/processRequestHeaders.ts
rest/restManager.ts
rest/sendRequest.ts
rest/simplifyUrl.ts
tests/rest.ts

Switching to bucket style rest system. (Much faster implementation)

Bucking Rest

---

helpers/roles/createRole.ts
helpers/roles/editRole.ts
plugins/permissions/src/roles/createRole.ts
plugins/permissions/src/roles/editRole.ts

Closes: #2529 
Upstream: https://github.com/discord/discord-api-docs/commit/45994752986782a6e0b488746c56d6108a186596
Docs: 
[Create Role](https://discord.com/developers/docs/resources/guild#create-guild-role-json-params)
[Edit Role](https://discord.com/developers/docs/resources/guild#modify-guild-role-json-params)

role name must be less than 100 characters

---

helpers/interactions/responses/deleteFollowupMessage.ts
helpers/interactions/responses/deleteOriginalInteractionResponse.ts

Closes: #2540
Upstream: https://github.com/discord/discord-api-docs/commit/8ebc79d47d554d0ba557e2a9103129ee83372fbc

delete follow up and original now support ephemeral

---

types/shared.ts

Closes: #2549 
Upstream: https://github.com/discord/discord-api-docs/commit/9077e797c446114f16aa2001c5b1966ebaac17ec

public thread can be in forum channel

---

bot.ts
plugins/permissions/src/permissions.ts
rest/cleanupQueues.ts
rest/createInvalidRequestBucket.ts
rest/createQueueBucket.ts
rest/processGlobalQueue.ts
rest/sendRequest.ts
types/discord.ts
util/bigint.ts

This PR run deno fmt, add missing import and change reverse snowflake's input type

Fix: typing

---

.vscode/settings.json

fix: .vscode set prettier and remove deno configs

---

.husky/pre-commit
package-lock.json
package.json
yarn.lock

Add eslint and prettier as git hooks

Add git hooks

---

.devcontainer/base.Dockerfile
.devcontainer/devcontainer.json

Works fine with codespaces. Should with local too.

Node migration - devcontainer

---

packages/eslint-config-discordeno/index.js
packages/eslint-config-discordeno/package.json

Stops eslint and prettier from mixing with each other.

Fix eslint config

---

.github/workflows/lint.yml

Adds a workflow to use ESLint and Prettier.
It shall also automatically fix any problems that arise and are fixable.

Add lint checks and autofixing workflow

---

bot.ts
handlers/guilds/GUILD_AUDIT_LOG_ENTRY_CREATE.ts
handlers/guilds/mod.ts
types/shared.ts

MASSIVE IMPACT TO BOTS!
close #2718

Audit Log Entry Event

---

packages/client/src/Structures/channels/Guild.ts
packages/rest/src/manager.ts

I have also formatted the code as it was impossible to navigate the code otherwise

Add rest helpers for templates

---

packages/types/src/discordeno.ts

I do not think implementation needs to be changed, but did not test it since I am not really sure how this turborepo and node stuff works.

🐛 - fix: types - slashcommands - add nsfw prop

---

packages/rest/src/manager.ts

Adds Template and Member Helpers to rest mangers.
BEWARE: There are several errors.

feat(rest helpers): Add template and member helpers.

---

packages/types/src/discord.ts

https://discord.com/channels/785384884197392384/1067265182776176690/1068189883073572924

Interaction types - remove member,channel,role from value type

---

packages/gateway/package.json
packages/gateway/src/Shard.ts
yarn.lock

This reverts commit ad306b0d0ae35a0d69b941fa8148dcf6da95214f.

Revert "fix: use isomorphic ws"

---

denoImportMap.json
packages/rest/package.json
packages/rest/src/manager.ts
packages/utils/package.json
packages/utils/src/urlToBase64.ts
yarn.lock

add fetch polyfill, that hope to remove after 30/04/2024

refactor: use node-fetch

---

packages/bot/src/transformers/channel.ts
packages/types/src/discord.ts

Closes: https://github.com/discordeno/discordeno/issues/2871

feat(bot,types): add `Channel.managed`

---

packages/client/src/typings.ts
packages/types/src/discord.ts
packages/types/src/shared.ts

Closes: https://github.com/discordeno/discordeno/issues/2857

feat(client,types): add `FormLayout` enum

---

packages/client/src/typings.ts
packages/rest/src/manager.ts
packages/types/src/discordeno.ts

closes: https://github.com/discordeno/discordeno/issues/2860

feat(client,rest,types): add `GetAuditLog.after`

---

packages/bot/src/transformers/toggles/guild.ts
packages/bot/src/transformers/toggles/role.ts
packages/client/src/Constants.ts
packages/client/src/Structures/guilds/Role.ts
packages/types/src/discord.ts
packages/types/src/shared.ts

Closes: https://github.com/discordeno/discordeno/issues/2859

feat(bot,client,types): add role subscriptions

---

.github/CODEOWNERS

This PR adds the leads to the CODEOWNER file.
Please let me know if I should have forgotten any file or directory, which you wish to also get notifications on.

chore(.github): add leads to CODEOWNERS

---

packages/rest/src/manager.ts
packages/rest/tests/unit/manager.spec.ts

The changes improve readability and performance by a small margin.

refactor(rest): simplify `manager.simplifyUrl`

---

packages/types/src/shared.ts

Closes: https://github.com/discordeno/discordeno/issues/2920

feat(types): add `ApplicationFlags.ApplicationAutoModerationRuleCreateBadge`

---

packages/types/src/shared.ts

Closes: https://github.com/discordeno/discordeno/issues/2926

feat(types)!: add guild expression & view monetization permissions

---

packages/bot/src/transformers/guild.ts
packages/types/src/discord.ts

Closes: https://github.com/discordeno/discordeno/issues/2927

feat(bot,types): add `Guild.maxStageVideoChannelUsers`

---

.github/workflows/site.yml
packages/benchmark/src/generateMessage.ts
scripts/generateMessage.js
website/docs/benchmark.mdx
website/package.json
website/src/components/Benchmark.tsx
website/yarn.lock

feat(site): add back benchmark to site (also change cpu model)

---

packages/types/src/shared.ts

- Added missing event docs
- Added a note for privileged intents
- Renamed `GuildBans` to `GuildModeration`
- Renamed `GuildEmojis` to `GuildEmojisAndStickers`

docs(types)!: update intents

---

packages/types/src/shared.ts

Closes: https://github.com/discordeno/discordeno/issues/2847

refactor(types)!: remove `PRIVATE_THREADS` guild feature

---

website/babel.config.js
website/docs/bigbot/step-3-gateway.md
website/package-lock.json
website/package.json
website/src/components/home/faq/index.tsx
website/src/components/home/features/feature.tsx
website/src/components/home/reviews/index.tsx
website/src/pages/index.tsx
website/src/styling/index.ts
website/yarn.lock

This PR fixes the site on mobile, and adds loading to give time for the JS to load.

Mobile responsiveness + add loading

---

packages/bot/src/bot.ts

Did not really test it since idk how turborepo works, but it should be fine.

🐛 - fix: bot pkg - gateway - prefer snakecase by default

---

packages/types/src/shared.ts

PS: Should we do like this or leave it as it is to prevent future changes unintentionally breaking it?

fix(types): MessageActivityTypes.JoinRequest

---

packages/bot/src/bot.ts
packages/gateway/src/Shard.ts

Check for Deno namespace and use its ws instead of node ws (without using eval like #3029)

fix(gateway): Use Deno's WebSocket

---

packages/gateway/src/Shard.ts

credit: @Yaikava for the updated detection method

fix(gateway): fix deno detection for ws

---

examples/README.md

The previous link lead to a `Page Not Found`.
> `Page Not Found`
> We could not find what you were looking for.
> Please contact the owner of the site that linked you to the original URL and let them know their link is broken.
I am assuming this new link is where it is meant to point to.

Update website URL in examples' README.md

---

packages/utils/src/bucket.ts

Bug(utils) Fix bucket refill after the first time

---

packages/bot/src/bot.ts
packages/bot/src/handlers/messages/MESSAGE_REACTION_ADD.ts
packages/types/src/discord.ts

Fixes https://github.com/discordeno/discordeno/issues/3073
Closes #3080

feat: add message_author_id to Message Reaction Add event

---

packages/gateway/src/manager.ts

The current calculation does not take the maximum Worker count into account. This PR should fix that.

fix(gateway): workerId calculation

---

packages/bot/src/bot.ts

fix(bot): bug with overriding lastShardId if it's not provided in createBot() options

---

packages/bot/src/transformers/interaction.ts

Add the missing customizer from #3139 that was declared in the typings but not used by the transformer

Add interactionDataOptions customizer

---

packages/bot/src/handlers/members/GUILD_MEMBERS_CHUNK.ts
packages/gateway/src/Shard.ts
packages/gateway/src/manager.ts
packages/gateway/src/types.ts

Removes the shard event `guildMemberChunk` added in #3149 and use the bot package handler instead

refactor(gateway)!: Remove `guildMemberChunk` shard event

---

.github/workflows/other-runtime-unit-test.yml

feat(ci): add cache for deno

---

website/src/components/home/reviews/index.tsx

Changed my bot's logo so had to change in the website feedback session but also just changed all other bots' guild counts as well

chore(website): update community feedback bots' guild counts and logo

---

packages/types/src/shared.ts

adding USE_EXTERNAL_SOUNDS and SEND_VOICE_MESSAGES.

adding document use of external sounds permission

---

.github/CODEOWNERS

Followup for #3199 while we discuss if the entire team should be able to approve PRs

feat: add individuals to codeowners

---

packages/bot/src/helpers.ts
packages/bot/src/transformers.ts
packages/bot/src/transformers/onboarding.ts
packages/rest/src/manager.ts
packages/rest/src/routes.ts
packages/rest/src/types.ts
packages/rest/src/typings/routes.ts
packages/types/src/camel.ts
packages/types/src/discord.ts
packages/types/src/discordeno.ts

Add support for guild onboarding.
fixes #2930
fixes #3072
fixes #3247 
closes #2937

feat(bot,rest,types): Add support for guild onboarding

---

packages/bot/src/bot.ts
packages/bot/src/handlers.ts
packages/bot/src/handlers/entitlements/ENTITLEMENT_CREATE.ts
packages/bot/src/handlers/entitlements/ENTITLEMENT_DELETE.ts
packages/bot/src/handlers/entitlements/ENTITLEMENT_UPDATE.ts
packages/bot/src/handlers/entitlements/index.ts
packages/bot/src/handlers/index.ts
packages/bot/src/handlers/invites/INVITE_CREATE.ts
packages/bot/src/helpers.ts
packages/bot/src/transformers.ts
packages/bot/src/transformers/application.ts
packages/bot/src/transformers/entitlement.ts
packages/bot/src/transformers/guild.ts
packages/bot/src/transformers/invite.ts
packages/bot/src/transformers/reverse/team.ts
packages/bot/src/transformers/sku.ts
packages/bot/src/transformers/team.ts
packages/bot/src/typings.ts
packages/rest/src/manager.ts
packages/rest/src/routes.ts
packages/rest/src/types.ts
packages/rest/src/typings/routes.ts
packages/types/src/camel.ts
packages/types/src/discord.ts
packages/types/src/discordeno.ts
packages/types/src/shared.ts

Like #3257, each commit is tied to an issue.
fixes #3020
fixes #3036 
fixes #3078
fixes #3105
fixes #3216
fixes #3219
fixes #3222
fixes #3228
fixes #3230
fixes #3231
fixes #3233
fixes #3234
fixes #3235
fixes #3236
fixes #3238
fixes #3242
fixes #3249
fixes #3251
fixes #3252
fixes #3253
fixes #3265

feat: api docs catchup part 2

---

packages/benchmark/package.json
packages/benchmark/src/benchmarks/transformers.ts
packages/types/src/discord.ts
yarn.lock

Make yarn resolve the `@discordeno/bot` package to the local one and not the npm one to don't get TS errors in the transformers benchmark

fix(benchmark): fix TS error on transformer benchmark

---

packages/benchmark/package.json
packages/benchmark/src/benchmarks/transformers.ts
packages/types/src/discord.ts
yarn.lock

Reverts discordeno/discordeno#3261

Revert "fix(benchmark): fix TS error on transformer benchmark"

---

.github/workflows/site.yml

ci: add merge group event to site

---

.github/workflows/lib-check.yml
.github/workflows/site.yml

lib check and site action wont run on everything, and block merge

ci: make required ci always run

---

.github/workflows/e2e-test.yml
.github/workflows/lib-check-e2e.yml
.github/workflows/lib-check.yml

ci: temp fix #3299

---

.github/workflows/docker-app-rest-passthrough.yml

It's not completely needed and may only cause issues.

fix: remove release-script for now

---

packages/gateway/src/Shard.ts

Currently the RTT (Round Trip Time) for a shard is calculated based on the first event that arrives after the OP 1 (Heartbeat) that Discordeno sends causing it to might get an incorrect value if the OP that triggers the code for the RTT calculation is a non 11 opcode (11 = HeartbeatACK)
This pr moves the calculation for the RTT to the HeartbeatACK opcode event to prevent an opcode like 0 (Dispatch) to mess-up the calculation
Fixes #2948

fix(gateway): Fix RTT calculation

---

packages/types/src/shared.ts

Add locale for `Spanish, LATAM` (`es-419`) and also `Indonesian` (`id`) that was missing
closes #3420

feat(types): Update locales

---

.github/CODEOWNERS

As requested [here](https://discord.com/channels/785384884197392384/785384884197392387/1233452262924353607)
> make me code owner then plz
> – Skillz

feat(.github): add Skillz to more codeowners

---

packages/rest/src/manager.ts
packages/rest/src/types.ts

According to [Get Answer Voters](https://discord.com/developers/docs/resources/poll#get-answer-voters), `getPollAnswerVoters` should return `users` object with an array of users.

fix(rest,type): getPollAnswerVoters return type

---

packages/types/src/shared.ts

Add audit log events for Guild Onboarding.
Upstream: [discord/discord-api-docs#6041](https://github.com/discord/discord-api-docs/pull/6041)
fixes #3607

feat(types): Add AuditLog events for onboarding

---

website/src/components/home/reviews/index.tsx

updated all bot guild counts, fixed the appy logo no longer working and also fixed a typo in aiig review

fixed typo and updated bot review guild counts

---

packages/types/src/discord.ts
packages/types/src/discordeno.ts

Document the position behavior for duplicate position values
- Upstream: https://github.com/discord/discord-api-docs/pull/6947
- fixes #3687

fix(types): Document the position behavior for duplicate position values

---

website/docs/bigbot/step-1-decisions.md
website/docs/bigbot/step-2-rest.md
website/docs/bigbot/step-3-gateway.md
website/docs/bigbot/step-4-bot.md
website/src/components/bigbotguide/GatewayFlowChart.tsx

This PR improves the big bot guide overall to make it more easier to understand and work with. Please lmk if you need anything to be added/modified to improve it further

docs: update big bot guide

---

.github/workflows/docker-app-rest-passthrough.yml

Add step in the CI to prevent an invalid serif file to be uploaded to the GitHub Security tab
(didn't test as it is push only and locally with `act` i wasn't able to get the action running)

fix(docker): Fix invalid snyk serif

---

packages/bot/src/transformers.ts
packages/bot/src/transformers/channel.ts
packages/bot/src/transformers/emoji.ts
packages/bot/src/transformers/toggles/channel.ts

Currently a bunch of proprieties are missing on the `Channel` type. This PR adds them

fix(bot): Add missing proprieties on `Channel`

---

packages/gateway/src/manager.ts

Currently the resharding code uses the `logger` from `@discordeno/utils` instead of the one in the `gateway` object. This is not wanted if a user has configured its own logger to be used instead

fix(gateway): Use passed in logger instead of the imported one

---

packages/bot/src/helpers.ts
packages/rest/src/manager.ts
packages/rest/src/routes.ts
packages/rest/src/types.ts
packages/rest/src/typings/routes.ts
packages/types/src/discordeno.ts

Add application emoji endpoints
- upstream: https://github.com/discord/discord-api-docs/pull/7010
- fixes #3773

feat(types,rest,bot): Add application emoji endpoints

---

packages/bot/src/transformers.ts
packages/bot/src/transformers/message.ts
packages/bot/src/transformers/types.ts
packages/types/src/discord.ts
packages/types/src/discordeno.ts

Add message forwarding
- upstream: https://github.com/discord/discord-api-docs/pull/6833
- fixes #3763

feat(bot,types): Add message forward

---

packages/bot/src/transformers.ts
packages/bot/src/transformers/scheduledEvent.ts
packages/bot/src/transformers/types.ts
packages/types/src/discord.ts
packages/types/src/discordeno.ts

Add recurrence rule to scheduled event.
- upstream: https://github.com/discord/discord-api-docs/pull/7058
- fixes: #3831

feat(bot,types): Add recurrence rule to scheduled event

---

packages/bot/src/helpers.ts
packages/bot/src/transformers.ts
packages/bot/src/transformers/voiceState.ts
packages/rest/src/manager.ts
packages/rest/src/types.ts

Add the voice state http endpoints.
- upstream: https://github.com/discord/discord-api-docs/pull/7061
- fixes #3840

feat(bot,rest): Add voice state http endpoints

---

packages/types/src/shared.ts

Update description for gateway 4003 close code
- Upstream: https://github.com/discord/discord-api-docs/pull/7059

fix(types): Update description for 4003 close code

---

packages/bot/src/bot.ts
packages/bot/src/handlers.ts
packages/bot/src/handlers/voice/VOICE_CHANNEL_EFFECT_SEND.ts
packages/bot/src/handlers/voice/index.ts
packages/bot/src/typings.ts
packages/types/src/discord.ts
packages/types/src/shared.ts

Add `voiceChannelEffectSend` gateway event
- Upstream: https://github.com/discord/discord-api-docs/pull/6025

feat(bot,types): Add `voiceChannelEffectSend` event

---

examples/advanced/.yarnrc.yml
examples/beginner/.yarnrc.yml
examples/minimal/.yarnrc.yml
examples/reaction-roles/.yarnrc.yml

The .yarnrc.yml file is needed or else when yarn runs it will attempt to use PnP

add .yarnrc.yml to advanced example solution

---

packages/bot/src/helpers.ts
packages/bot/src/transformers.ts
packages/bot/src/transformers/activity.ts
packages/bot/src/transformers/types.ts
packages/rest/src/manager.ts
packages/rest/src/routes.ts
packages/rest/src/types.ts
packages/rest/src/typings/routes.ts
packages/types/src/discord.ts

Add get activity instance endpoint and DiscordActivityInstance
- Upstream: https://github.com/discord/discord-api-docs/pull/6981

feat(bot,rest,types): Add get activity instance endpoint

---

packages/bot/src/transformers/toggles/member.ts
packages/types/src/shared.ts

Add new member flags:
- `IsGuest`
- `StartedHomeActions`
- `CompletedHomeActions`
- `AutomodQuarantinedUsername`
- `DmSettingsUpsellAcknowledged`
- Upstream: https://github.com/discord/discord-api-docs/pull/7113

feat(bot,types): Add new member flags

---

packages/bot/src/transformers/types.ts
packages/types/src/discord.ts

- Upstream: https://github.com/discord/discord-api-docs/pull/7116

feat(bot,types): Add new fields to message snapshots

---

packages/types/src/discord.ts

- Upstream: https://github.com/discord/discord-api-docs/pull/7095

feat(types): Add amazon music connection

---

packages/bot/src/transformers/application.ts
packages/types/src/discord.ts

- Upstream: https://github.com/discord/discord-api-docs/pull/7027

feat(bot,types): Add null to application urls

---

packages/bot/src/transformers.ts
packages/bot/src/transformers/member.ts
packages/bot/src/transformers/types.ts
packages/types/src/discord.ts

Add banners to guild members
- Upstream: https://github.com/discord/discord-api-docs/pull/6986

feat(types,bot): Add banners to members

---

website/docusaurus.config.ts
website/package.json
website/yarn.lock

Add the redirect used in info messages by the Typescript desired properties helpers
And update docusaurus dependencies

website: Add the /desired-props redirect

---

packages/bot/src/helpers.ts
packages/rest/src/manager.ts
packages/rest/src/types.ts
packages/types/src/discordeno.ts

Add `GetEntitlements.excludeDeleted` query param for the list entitlements endpoint
Add the get entitilement endpoint
Update comment on `GetEntitlements .excludeEnded`
- Upstream: https://github.com/discord/discord-api-docs/pull/7279

feat(types,rest,bot): Document new entitlement endpoint behavior

---

packages/types/src/discord.ts

Add the crunchyroll connection to `DiscordConnectionServiceType`

feat(types): Add the crunchyroll connection

---

packages/bot/src/bot.ts
packages/bot/src/commandOptionsParser.ts
packages/bot/src/desiredProperties.ts
packages/bot/src/events.ts
packages/bot/src/helpers.ts
packages/bot/src/transformers.ts
website/docs/desired-properties.md

Currently when you hover something like a bot helper you get something like:
```ts
BotHelpers<CompleteDesiredProperties<{ ... }>, DesiredProprietiesBehavior.RemoveKey, Bot<CompleteDesiredProperties<{ ... }>, DesiredProprietiesBehavior.RemoveKey>>.sendMessage(channelId: BigString, options: CreateMessageOptions) => Promise<SetupDesiredProps<Message, CompleteDesiredProperties<{ ... }>, DesiredProprietiesBehavior.RemoveKey>>
```
However we can simplify this *a bit* removing the TBot generic type.
The result is something like:
```ts
BotHelpers<CompleteDesiredProperties<{ ... }>, DesiredProprietiesBehavior.RemoveKey>.sendMessage(channelId: BigString, options: CreateMessageOptions) => Promise<SetupDesiredProps<Message, CompleteDesiredProperties<{ ... }>, DesiredProprietiesBehavior.RemoveKey>> …
```

feat(bot): Remove some clutter from desired proprerties intellisense

---

.github/dependabot.yml

Skillz talked about wanting the dependabot prs to only be made every month so this pr changes it to monthly!

fix(dependabot): switch to monthly dependencie updates

---

website/src/components/home/reviews/index.tsx

CactusFire no longer uses this library in any of its microservices

Remove CactusFire from reviews section

---

packages/rest/src/manager.ts

Currently the code that handles proxy errors is doing a `.text()` on the response text if the status code is not in the range of 2xx. However if `.text()` (somehow) fails we then call `.json()` which will always fail due to the fact that 1. we already consumed the body with `.text()` and 2. if a `.text()` couldn't read the body, then `.json()` won't either.
So this pr changes the error handling code to just use `.text()`
This pr also moves the `await response.arrayBuffer()` of `sendRequest` when the error is a 429 as currently it is possible for it to not get called and so leak the response body (see: https://github.com/nodejs/undici#garbage-collection)

fix(rest): Simplify proxy error code & avoid leaking response

---

packages/utils/src/images.ts

`memberBannerUrl` is missing from utils

feat(utils): Add `memberBannerUrl`

---

packages/utils/src/logger.ts
packages/utils/tests/logger.spec.ts

Most of the time is annoying & does not give a very clear benefit to anyone

chore(utils)!: Remove logger code related to Depth

---

packages/gateway/src/manager.ts

The old formula does not spread the shards correctly over the workers, you will get something like 1 shard on worker 0 and 7 shards on worker 1
The new formula does it correct :)

fix(gateway): wrong calculation in calculateWorkerId()

---

packages/types/src/discord/message.ts

- upstream: https://github.com/discord/discord-api-docs/pull/7253

feat(types): Add `HasSnapshot` flag to Message

---

packages/types/src/discord/application.ts

Reorder proprieties in application.ts to match the order discord puts them in.
Also remove a link in comments to match other comments

refactor(types): reorder properties in DiscordApplication

---

packages/bot/src/transformers/automodActionExecution.ts
packages/bot/src/transformers/types.ts
packages/rest/tests/e2e/automod.spec.ts
packages/types/src/discord/autoModeration.ts

Also fix some comments to be more clear

fix(types)!: Fix optionals for some props in auto moderation.

---

packages/benchmarks/src/benchmarks/transformers.ts
packages/bot/src/desiredProperties.ts
packages/bot/src/transformers/component.ts
packages/bot/src/transformers/reverse/component.ts
packages/types/src/discord/components.ts
packages/types/src/discordeno.ts

- feat(bot): Add desiredProperties for components, as well as media gallery items and unfurled media items
- fix(types)!: Rename the following types to match the newly updated discord docs:
- InputText to TextInput
- SelectMenu to StringSelect
- SelectMenuUsers to UserSelect
- SelectMenuRoles to RoleSelect
- SelectMenuMentionable to MentionableSelect
- SelectMenuChannels to ChannelSelect
- Update some JSDOC comments to match the new discord docs
Implements: https://github.com/discordeno/discordeno/issues/4173

feat(types,bot)!: Add desiredProperties for components

---

packages/types/src/discord/components.ts

- upstream: https://github.com/discord/discord-api-docs/pull/7537

fix(types): Add missing limits on alts for media

---

packages/gateway/src/manager.ts
packages/utils/src/utils.ts
packages/utils/tests/utils.spec.ts

Fixes unexpected TypeError caused due to debug call to `JSON.stringify` using json-unserializable values.
closes #4196

fix: Unexpected TypeError in `GatewayManager.requestMembers`

---

packages/gateway/src/manager.ts

feat(gateway): add options.spreadShardsInRoundRobin to spread shards in a round-robin manner

---

packages/types/src/discord/reference.ts
packages/utils/src/images.ts
packages/utils/tests/images.spec.ts

- upstream: https://github.com/discord/discord-api-docs/pull/7568
- upstream: https://github.com/discord/discord-api-docs/pull/7404

feat(utils): animated webp emojis

---

packages/types/src/discord/webhookEvents.ts

- upstream: https://github.com/discord/discord-api-docs/pull/7599

feat(types): Add application deauthorized webhook event

---

packages/types/src/discordeno.ts

- upstream: https://github.com/discord/discord-api-docs/pull/7598

fix(types): update InteractionCallbackData flags

---

packages/bot/src/transformers/application.ts
packages/bot/src/transformers/types.ts
packages/types/src/discord/application.ts

- upstream: https://github.com/discord/discord-api-docs/pull/7613

feat(types,bot): approximate_user_authorization_count

---

packages/bot/src/desiredProperties.ts
packages/bot/src/transformers/component.ts
packages/bot/src/transformers/reverse/component.ts
packages/bot/src/transformers/types.ts
packages/types/src/discord/components.ts

- upstream: https://github.com/discord/discord-api-docs/pull/7611

feat(types,bot): Add attachment_id to UnfurledMediaItem

---

docker-apps/rest-passthrough/Dockerfile
docker-apps/rest-passthrough/package.json
docker-apps/rest-passthrough/yarn.lock

Upgrade the rest proxy to use Node.js version 20 and update related dependencies

Update rest proxy to Node.js v20 and dependencies

---

packages/types/src/discordeno.ts

- upstream: https://github.com/discord/discord-api-docs/pull/7636

fix(types): EditGuildOnboarding params are optional

---

packages/bot/src/desiredProperties.ts
packages/bot/src/transformers/invite.ts
packages/bot/src/transformers/reverse/member.ts
packages/bot/src/transformers/toggles/guild.ts
packages/bot/src/transformers/types.ts
packages/types/src/discord/guild.ts
packages/types/src/discord/invite.ts

- upstream: https://github.com/discord/discord-api-docs/pull/6247
> [!WARNING]
> This is breaking because now a member joined_at is nullable

feat!: Add invite flags for guest invites

---

packages/types/src/discordeno.ts

And sort them to match the table on the discord docs

fix(types): Add missing props to ExecuteWebhook

---

packages/types/src/discord/gateway.ts

-upstream: https://github.com/discord/discord-api-docs/pull/7674

feat(types): Add new rich presence url & status display type fields

---

website/docs/desired-properties.md
website/docs/examples/deno.md
website/docs/getting-started.md

And also update deno example to use v21

docs: Include notice of strictNullChecks being required

---

packages/bot/src/transformers/types.ts
packages/types/src/discord/user.ts

- upstream: https://github.com/discord/discord-api-docs/pull/7701

api-docs: Update the description for identity_enabled to be clearer

---

packages/bot/src/transformers/toggles/member.ts
packages/types/src/discord/guild.ts

- upstream: https://github.com/discord/discord-api-docs/pull/7699

api-docs: Document AUTOMOD_QUARANTINED_GUILD_TAG member flag

---

packages/types/src/discordeno.ts

* upstream: https://github.com/discord/discord-api-docs/pull/7267

api-docs: Add IS_VOICE_MESSAGE to CreateMessageOptions

---

packages/bot/src/helpers.ts
packages/rest/src/manager.ts
packages/rest/src/routes.ts
packages/rest/src/types.ts
packages/rest/src/typings/routes.ts

- upstream: https://github.com/discord/discord-api-docs/pull/7722

api-docs!: remove editGuildMFA

---

packages/types/src/discordeno.ts

- upstream: https://github.com/discord/discord-api-docs/pull/7517

api-docs: Fix payload for modify current user voice state

---

website/package.json
website/src/components/architecture/BaseFlowChart.tsx
website/src/components/architecture/FlowChart.tsx
website/src/components/architecture/FlowChart2.tsx
website/src/components/architecture/FlowChart3.tsx
website/src/components/architecture/FlowChart4.tsx
website/src/components/bigbotguide/GatewayFlowChart.tsx
website/src/components/header/index.tsx
website/src/components/home/features/feature.tsx
website/src/components/home/features/index.tsx
website/src/types.ts
website/yarn.lock

The bump also includes `reactflow` -> `@xyflow/react` (https://reactflow.dev/learn/troubleshooting/migrate-to-v12)

build(deps): Migrate to React Flow v12 and update website dependencies

---

packages/bot/src/transformers/presence.ts

Despite the type not having the optional, it may get called with an partial object

fix(bot): Check nullable in transformPresence

---

packages/bot/src/transformers.ts

This allows us to edit the transformers in bulk without many issues

refactor: Use TransformerFunction to define transformers

---

packages/rest/src/types.ts

- upstream: https://github.com/discord/discord-api-docs/pull/7792
- fixes #4424

docs(rest): Update documentation for get invites endpoint

---

packages/benchmarks/src/benchmarks/memory.ts
packages/bot/src/events.ts

refactor(bot)!: Remove debug event
