- README.md
- module/client.ts
This PR adds the ability to update the event handler's live without having to restart the entire bot. Simple call the `updateEventHandlers` function and pass in a new eventHandlers object similar to the one passed when starting the bot and it will update. Very useful for fixing tiny mistakes without having to reboot.
> reload events handlers

- README.md
- module/shardingManager.ts
- structures/channel.ts
- structures/guild.ts
- structures/member.ts
- structures/message.ts
- structures/role.ts
- structures/user.ts
- types/member.ts
- types/message.ts
- types/options.ts
- utils/permissions.ts
This PR adds some major refactors and user experience improvements to make your lives easier as developers. For example, simply passing the guild and member data to create a member isntead of calculating role data from a guild and passing 5 arguments. Now its just `createMember(memberDataFromDiscord, guild)` 🎉 
This PR also makes the usage of the library easier as you can see much better what the type of any variable instead of trying to understand the full object.
- Adds member.guildID
- Adds member.guild()
- Adds channel.hasPermission(id, permissions)
- Caches all users and members when mentioned
- fix: No longer create new users in createMessage instead get the user from cache which is done inside shardingManager when the payload is received
**Before**
**Now:**
This changes the public …
> V3: Refactor export type into interfaces + enhancements

- module/basicShard.ts
- module/client.ts
- module/shardingManager.ts
- types/options.ts
- utils/utils.ts
This PR is a major feature enhancement without implementing any breaking changes but due to it's massive effect I want to give it some time for other devs to review and test.
**Understanding**
Until now Discordeno had only 1 sharding solution that was designed for large bots. This solution used the Deno Workers(which are still unstable) but it allowed insanely huge bots to work as well. However, for smaller bots, this increased a huge amount of complexity. Dealing with workers and different threads is not an easy concept so to solve this I created a second alternative sharding for now being called `basicShard`. 
**Effects**
If your bot has less than 25 shards aka less than 25,000 servers you will be automatically included in the basic shard system. This means you no longer use Deno …
> Alternative sharding solution for smaller bots

- module/shardingManager.ts
- types/options.ts
- utils/cache.ts
This is useful to compare the presence payload before the update and the new presence payload. Here is a simple use-case below:
```ts
import Client, { botID } from "../Discordeno/module/client.ts";
import { sendMessage } from "../Discordeno/handlers/channel.ts";
import { Intents } from "../Discordeno/types/options.ts";
import config from "./config.ts";
Client({
token: config.token,
intents: [Intents.GUILD_MESSAGES, Intents.GUILDS, Intents.GUILD_PRESENCES],
eventHandlers: {
ready: () => {
console.log(`Logged!`);
},
messageCreate: (message) => {
if (message.content === "!ping") {
sendMessage(message.channel, "Pong");
}
},
presenceUpdate: (oldPresence, newPresence) => {
if (!oldPresence) return;
if (oldPresence.status !== 'offline' && newPresence.status === 'offline') {
console.log(`User …
```
> Add oldPresence to presenceUpdate event

- src/types/guild.ts
Due to changes in v7 of which type you allow for channel type, creating channels does not work anymore.
This PR removes the channel types in types/guild.ts, and uses the channel types from types/channel.ts instead.
> [v7] Fix broken createGuildChannel

- src/handlers/guild.ts
Renamed leave() to leaveGuild() to remove ambiguity.
> Rename leave() to leaveGuild() to remove ambiguity

- docs/config.js
In the Documentation, the DocsUrl is not correctly set. This makes the `Edit on github ` not show the Correct Location. This Pr will fix this.
> docs(Correct docsUrl)

- src/module/basicShard.ts
Fixes 
Resume connect of shard socket if lost between heartbeats.
The socket can be closed in between heartbeats, and the connection needs to be recreated. [Here](https://github.com/Skillz4Killz/Discordeno/blob/master/src/module/basicShard.ts#L209-L212) we just return and the bot stops working.
**Status**
_Testing more thoroughly with my bot at the moment_
> fix: resume connect of shard socket if lost between heartbeats

- src/controllers/members.ts
The event *guildMemberRemove* is triggered twice.
**Status**
> fix: guildMemberRemove event triggered twice

- src/handlers/channel.ts
- src/handlers/message.ts
- src/handlers/webhook.ts
Add `await` to all non-resolved botHasChannelPermissions calls.
Closes #174 
Closes #173 
**Status**
> Resolve promise for all botHasChannelPermissions()

- src/module/requestManager.ts
The Retry-After header's value is in seconds (sent by the API); however, Discordeno treats the value as milliseconds instead of seconds. This PR converts the seconds received by API to ms.
> The Retry-After header is now based in seconds instead of milliseconds (e.g. 123 means 123 seconds)
v8 CHANGELOG: https://discord.com/developers/docs/change-log
**Status**
> Convert Retry-After to ms

- src/controllers/bans.ts
- src/controllers/cache.ts
- src/controllers/channels.ts
- src/controllers/members.ts
- src/controllers/messages.ts
- src/controllers/misc.ts
- src/controllers/reactions.ts
- src/controllers/roles.ts
- src/handlers/guild.ts
- src/handlers/message.ts
- src/structures/guild.ts
- src/structures/member.ts
- src/types/member.ts
- src/utils/cache.ts
- src/utils/permissions.ts
This PR moves the guild.members to a cache.members to optimize ram usage. With 100 guilds per user, usernames, discriminators, etc were all duplicated and eating up ram. Moving to cache makes that all saved ram.
**Status**
> [BREAKING] move guild.members to cache.members

- src/handlers/channel.ts
- src/handlers/guild.ts
- src/handlers/member.ts
- src/handlers/message.ts
- src/handlers/webhook.ts
- src/utils/permissions.ts
- tests/mod.test.ts
This pr changes all Permissions to Permission type allowing users to have 1 form to interact with the lib in a consistant manner and still keeping all th ebenefits. Note this will actually improve it as u no longer need to import the Permissions enum.
**Status**
> [BREAKING] Permission consistency

- docs/package.json
Since it was decided to change the Repository name to a small "d" the Repository base URL for the Documentation is outdated again.
**Status**
> Discordeno Repository URL got changed again.

- docs/src/djs.md
- docs/src/gettingstarted.md
- docs/src/stepbystep/createcommand.md
- docs/src/stepbystep/createevent.md
Since the discordeno support for x.nest.land gets officially dropped all links may be changed to deno.land/x/
**Status**
> x.nest.land to deno.land/x/

- src/types/guild.ts
Since Discords v8 update permission allow/deny are send as strings now. Change was requested by Skillz4Killz.
**Status**
> Allow/Deny changed to Strings in v8

- src/util/permissions.ts
hasChannelPermissions is using a wrong function at the end. It should check for the member permission and not for the bot permission.
**Status**
> fix: hasChannelPermissions

- docs/src/stepbystep/createcommand.md
"Let's set it to to 5" -> "Let's set it to 5"
(Documentation fix)
**Status**
> Fixed typo

- src/api/controllers/guilds.ts
- The `GUILD_UPDATE` controller checks if the `data.t` is NOT `GUILD_CREATE`, this PR replaces `GUILD_CREATE` to `GUILD_UPDATE`.
> fix: replace incorrect check for GUILD_UPDATE controller

- src/api/handlers/message.ts
- src/util/constants.ts
Reference: https://discord.com/developers/docs/resources/channel#add-pinned-channel-message
> fix: outdated pin & unpin handlers and endpoints

- src/api/handlers/webhook.ts
- src/types/webhook.ts
Please describe the changes this PR makes and why it should be merged:
upsertSlashCommand() does not actually edit the slash command. This is fixing this issue
Status
Code changes have been tested against the Discord API, or there are no code changes
Semantic versioning classification:
This PR changes the library's interface (methods or parameters added)
This PR includes breaking changes (methods removed or renamed, parameters moved or removed)
This PR only includes non-code changes, like changes to documentation, README, etc.
> fix: slash command edit functions

- src/types/options.ts
Add JSDoc comments for almost all documented events.
**Status**
> docs: add jsdoc comments for documented event handlers

- src/types/message.ts
- Make `Attachment.height` and `Attachment.width` optional.
Reference: https://github.com/discord/discord-api-docs/pull/2214 (NOT MERGED)
**Status**
> types(message): make attachment dimensions optional

- src/api/controllers/members.ts
- src/api/structures/member.ts
- src/types/guild.ts
- src/types/options.ts
- Added "membershipScreeningPassed" event to `EventHandlers`.
- Emit "membershipScreeningPassed" event when the `member.pending` field is true in "GUILD_MEMBER_UPDATE" event.
Closes: #462
> feat(controllers): add membershipScreeningPassed event

- src/api/handlers/guild.ts
- src/types/guild.ts
- src/util/constants.ts
Reference: https://github.com/discord/discord-api-docs/pull/2396
**Status**
code changes
README, etc.
> feat(handlers): add Membership Screening

- src/api/controllers/roles.ts
My bad, I accidently reverted that one. The role needs to be deleted from cache before emitting the event.
> fix(controllers): delete role from cache before emitting the event

- src/ws/shard.ts
I am still confused as to why the WebSocket connection is closed with close code `4009`... any particular reason why this is done? @Skillz4Killz
> fix(ws/shard): use WebSocket#close() instead of WebSocket#send() to close connection

- README.md
It is ambiguous or vague to the users whether Discordeno follows Semver or not... this changes that; explicitly state that Discordeno follows SemVer to enable backward compatibility.
> docs(README): mention usage of SemVer

- docs/src/README.md
resources is a plural word but is being used as a singular word here
> docs(README): fix grammatical error

- src/api/handlers/webhook.ts
> fix(handlers/webhook): do not add Date.now() to 900000 ms in executeSlashCommand()

- src/api/controllers/CHANNEL_PINS_UPDATE.ts
- src/api/handlers/message.ts
Changes:
- Return a promise that resolves to collection of UserPayload mapped by their ID prop
- To maintain consistency, the return type is only a collection of UserPayload as values, not a mixture of Member objects and UserPayload objects
Closes #606
> feat(handlers/message): change getReactions() to use collection

- src/helpers/mod.ts
Removing rawAvatarURL export since it was removed in #743
> fix(helpers) Remove rawAvatarURL export

- src/rest/process_request_headers.ts
Discord uses different headers for global sad
> fix ratelimit headers again

- .github/CONTRIBUTING.md
From what I can see, majority of the contributors are not familiar with Conventional Commits and some of the commits are merged without proper guidelines (going against Contributing), we should just remove this altogether.
> Remove PR title examples

- src/types/messages/message_sticker.ts
Reference: https://github.com/discord/discord-api-docs/commit/b9b8db2ed548dded2a50824a68ea638d735737c6
> remove(types): previewAsset from MessageSticker

- src/types/gateway/ready.ts
BREAKING: since Tuesday, 6 April 2021, private_channels field has been undocumented by @night. Reference commit: https://github.com/discord/discord-api-docs/commit/f36156dbb641f5c4d4f4593f345bfd6e27fdee08
> remove(types): privateChannels field from Ready

- src/types/users/user_flags.ts
Reference: https://github.com/discord/discord-api-docs/commit/9293f0d490ac6acf9d627e429e5a8131b303b528
BREAKING: The flag "System" has been removed from the documentation on 9 April 2021
> remove(types): System user flag

- LICENSE
We have done a lot of thinking and decided it is the best for Discordeno to switch to the Apache 2.0 License.
In order to change the license we need the approves of all code authors whose code we are currently using. 
@existentiality @TriForMine @ayntee @rigormorrtiss please approve this pull request to give us permission to change the license.
If you should have any questions regarding the change feel free to discuss it on our discord server: https://discord.gg/5vBgXk3UcZ
> change: LICENSE switch to Apache 2.0

- src/cache.ts
The title explains it. The cache was using string to key emojis, made that bigints since it's already converted to bigints from string-snowflakes.
> fix(cache): emojis to use bigint for key

- src/types/messages/message.ts
> fix(types): message.stickers is an array

- src/structures/guild.ts
since custom emojis always have an id we don't need a fall back to name. hehehe
> change: how emojis cached

- src/rest/process_queue.ts
- src/rest/rest.ts
This is important so failed requests do actually get rejected. This PR is just to make it typesafe too.
> change: make RestRequest.reject required

- src/types/discordeno/event_handlers.ts
Changed `Sent when a user uses a Slash Command` to `Sent when a user uses a Slash Command (type 2) or clicks a button (type 3)` as interaction create event also triggers when a button is clicked now. The user can determine what triggered the event by checking the value of interaction.type in the event
> add: eventHandlers interaction clarify type property

- src/types/channels/threads/thread_member.ts
The id and user_id fields are omitted on the member sent within each thread in the `GUILD_CREATE` event.
- Reference: https://github.com/discord/discord-api-docs/pull/3097﻿
- Files Diff: https://github.com/discord/discord-api-docs/pull/3097/files#diff-160acb4654c611c67c4ee46b2ce5dda2be82212af8d1d00cd0256ef6edda1e95R543
> fix(types): mark id, userId as optional in ThreadMember

- src/types/messages/message_sticker.ts
Reference: https://github.com/discord/discord-api-docs/commit/82e238645e5b80dbb898396fccaf1101716650eb﻿
> docs(types): add clarification for guild stickers for MessageSticker#tags

- src/types/messages/message.ts
- src/types/messages/message_sticker.ts
- docs(types): deprecate stickers field in Message
- fix(types): update MessageSticker fields
Reference:	https://github.com/discord/discord-api-docs/pull/3127
Commit:		https://github.com/discord/discord-api-docs/commit/9c3577f6ca35904462adf8d57c4346afd2a6bcf0
> Update MessageSticker fields and deprecate Message#sticker

- src/types/interactions/commands/application_command_interaction_data.ts
Make the `id` and `name` required in ApplicationCommandInteractionData interface. Closes #1060
> fix: make id and name required in ApplicationCommandInteractionData

- src/types/codes/json_error_codes.ts
> Added code `20035`, which can be obtained in the following ways:
> 
>     * Creating a private thread in a server that has only public thread support.
> 
>     * Using `auto_archive_duration: 4320`/`10080` for public threads (without `THREE_DAY_AUTO_ARCHIVE` nor `SEVEN_DAY_AUTO_ARCHIVE`).
> 
> 
> * Both cases happen when running them in a library testing server (which has `THREADS_ENABLED`) that doesn't meet the criteria for the `THREADS_ENABLED_TESTING` feature. I'm not aware of this being reproducible elsewhere until general release.
> 
> Credits to @ckohen for finding the error code and the routes in which they appear.
Reference: discord/discord-api-docs#3189﻿
> feat(types/codes): add 20035 code to DiscordJsonErrorCodes

- src/cache.ts
- src/structures/channel.ts
- src/structures/guild.ts
- src/structures/member.ts
- src/structures/message.ts
- src/structures/role.ts
- src/structures/voice_state.ts
This pr adds a new feature to the library for advanced bot developers. 
The purpose of this feature is for optimizing memory in an easier way than having to customize structures and overriding them. For example, if you simply want to remove some properties you don't use, this would be the ideal way.
```ts
// This example is just to easily show you but you should ideally use an array and loop over the array
cache.requiredStructureProperties.channels.add("topic");
cache.requiredStructureProperties.channels.add("id");
```
This would now make it so that your channels will are ONLY storing the `topic` and `id` properties and nothing else.
> feat: requiredStructureProperties

- src/types/messages/message_flags.ts
This is just a report of typo, but applying this causes a BRAKING CHANGE of interface.
> fix: typo in EditMessage.flags

- src/ws/handle_on_message.ts
Sets the shard heartbeat property `lastReceivedAt` when `HEARTBEAT_ACK` is received.
> fix(ws): set lastReceivedAt when HeartbeatACK is received

- src/rest/run_method.ts
Advised by luca to add a ts-ignore until they fix this in deno deploy.
Closes #1088
> fix: prevent deno deploy from crashing on stack capture #1088

- README.md
Fix README example
(Explanation: the function `enableCachePlugin` does NOT modify the type of variable `bot` from type `Bot` to `BotWithCache`, the function `enableCachePlugin` only return the type `BotWithCache`)
Fix benchmark submodule pointing to invalid commit
> fix README example and benchmark submodule

- src/helpers/members/editMember.ts
- src/transformers/member.ts
- src/transformers/message.ts
- src/types/messages/message.ts
- src/types/messages/mod.ts
- src/types/mod.ts
- src/types/stickers/mod.ts
Continuation of #1862 Document Guild Member Timeout
Fix member transformer in src/transformers/message.ts
Fix message interface in src/types/messages/message.ts
Export * from stickers.
> Fix member transformer, interface (continuation of Document Guild Member Timeout)

- src/types/interactions/commands/applicationCommandTypes.ts
As much as this seems like a tiny PR. It gets really confusing, as most of the time you should use `ChatInput` instead of `Message` but that is not directly explained.
> Add descriptions for ApplicationCommandTypes

- tests/webhooks/sendWebhook.ts
Waits for server confirmation of message send before response, and returns the created message body (defaults to false; when false a message that is not saved does not return an error)
> fix send a message with a webhook test

- tests/deps.ts
- tests/invite/deleteInvite.ts
fix delete invite test
`deleteInvite` function return `Promise<void>`, therefore the correct way to test is to check if `getInvite` function THROWS/REJECTS
> fix(tests): delete invite 

- .github/CODEOWNERS
Ayntee is currently not here so we can remove him from codeowners for now and add him back when he is back.
> chore(.github): remove @ayntee from codeowners

- src/helpers/guilds/getWelcomeScreen.ts
discord/discord-api-docs@00a0ae2
Closes: #1905
> discord-api-docs: document the required permission for retrieving the welcome screen when disabled

- src/types/codes/jsonErrorCodes.ts
discord/discord-api-docs@a4be17f
Closes: #1915
> discord-api-docs: Document error code 30046 (old message edit rate limit)

- src/types/messages/messageFlags.ts
discord/discord-api-docs@2d13f67
Closes: #1918
> discord-api-docs: Document message flag FAILED_TO_MENTION_SOME_ROLES_IN_THREAD

- plugins/permissions/src/messages/create.ts
Fix permissions plugin, that throws an error about message content length when it's valid instead of when it's invalid.
> fix(permissions): `editMessage` content length check

- site/static/CNAME
Currently always when deploying the website the `CNAME` file gets deleted, therefore the website won't be accessible from `discordeno.mod.land` after every deploy.
> fix(cname): website domain not getting set

- src/transformers/message.ts
- src/types/members/guildMemberUpdate.ts
- Changed the type of `GuildMemberUpdate#communicationDisabledUntil` to number (this is a temporary fix it will be changed soonTM)
- Now parsing the `communicationDisabledUntil` in the message transformer
> fix(types): handle `communicationDisabledUntil` correctly

- types/messages/components/inputTextComponent.ts
Closes: #2018 
Upstream: https://github.com/discord/discord-api-docs/commit/ba99e8c824a10c6398aaf918e78bc17607fb7cad
Note: Label is already NOT optional, so I just add the docs link
> docs(types): add link for `InputTextComponent`

- types/messages/components/messageComponentTypes.ts
Closes: #2019 
Upstream: https://github.com/discord/discord-api-docs/commit/bc4cfa8fa1b85b80bde2e78179d0c7413c385157
Note: We already added Text Input to Component Types so I just update the jsdoc comments
> docs(types): update `MessageComponentTypes` variant description

- types/guilds/scheduledEvents.ts
Closes: #2010 
Upstream: https://github.com/discord/discord-api-docs/commit/3ed90459752015a9fa43fb185a75d89431ec2112
Note: The change is making creator_id optional but for some reason we already make it optional but we forgot it's nullable so I make it nullable :)
> fix(types): `ScheduledEvent#creator_id` is nullable

- types/channels/threads/threadMetadata.ts
Closes: #2003 
Upstream: <https://github.com/discord/discord-api-docs/commit/a783ca92c1150e1e2b7a510ce25fdb4de9ced1fd>
Note: Compatible with #2056
Reference for making locked NOT optional: <https://discord.com/developers/docs/resources/channel#thread-metadata-object-thread-metadata-structure>
> fix(types): `ThreadMetadata#create_timestamp` is optional and nullable & `locked` is not optional

- transformers/channel.ts
- types/channels/channel.ts
Note: `invitable` and `createTimestamp` should be and already in `ThreadMeatadata`, and shouldn't be in `Channel`
> fix(types): `invitable` & `createTimestamp` are in `ThreadMetadata` and not in `Channel`

- helpers/channels/createChannel.ts
- helpers/channels/editChannel.ts
Closes: #1971 
Upstream: https://github.com/discord/discord-api-docs/commit/7c0249a3c41b7596f7a7a4c6d2b3b7e4a6ac307c
Note: feel free to discuss if you prefer `null` or `undefined` or `"0"`
> * In each overwrite object, the allow and deny keys can be omitted or set to null, which both default to "0".
> fix(helpers): when creating/modifying a channel `permission_overwrites` can omit the `allow` and `deny`

- types/interactions/commands/applicationCommandInteractionData.ts
Closes: #2017
Upstream: <https://github.com/discord/discord-api-docs/commit/b268fe763a1e7707cac868aecc60957a8b8260aa>
Note: ApplicationCommandOption type already have ATTACHMENT, and transformInteractionDataResolved function already resolve ATTACHMENT
> docs(types): add `attachment` to `InteractionData` 

- helpers/messages/editMessage.ts
- transformers/embed.ts
- types/messages/editMessage.ts
Note: I changed `transformer/embed.ts` because I looked at `helpers/messages/editMessage.ts` and see `provider: embed.provider` `fields: embed.fields` because both of them's properties are only one word therefore no camelCase to snake_case manual conversion needed
> fix(types, helpers)!: EditMessage helper transformer & change `Embed` to `DiscordenoEmbed`

- gateway/gateway_manager.ts
- gateway/handleOnMessage.ts
- gateway/identify.ts
- gateway/mod.ts
- gateway/processGatewayQueue.ts
- gateway/resume.ts
- gateway/safeRequestsPerShard.ts
- gateway/sendShardMessage.ts
- gateway/shard.ts
This PR will close #1886 
It improves on some minor but crucial aspects of rate limiting in the gateway side.
- Instead of hardcoding 120/m we now make it dynamic so that bots can override in case discord will bump their max amount or such.
- Instead of hardcoding the reserved requests for heartbeating we now dynamically calculate this based on the interval discord will provide. This protects against any possible change discord may decide to change the heartbeat interval.
- Optimized the delay. Before when you hit the max, we just hardcoded a 1 min wait to reset the timer since discord didn't provide a good value to know. Now we will reset based on the amount of time left since the first request was sent.
- Changed gateway/ws.ts to gateway/shard.ts. The filename was just weird.
> fix(gateway): rate-limit handling

- site/docs/nodejs/Structures/create-structure.md
The previous links would lead to a 404 because of a capitalization issue.
Tested and new links point to the correct pages.
> docs: fix typo in create-structure urls

- plugins/permissions/src/interactions/mod.ts
Modal titles must have a length between 1 and 45 characters.
This adds a check to the permissions plugin.
Reference: https://github.com/discord/discord-api-docs/pull/4649
Closes: #2123
> feat(plugins): validate interaction response title

- bot.ts
- helpers/templates/createGuildTemplate.ts
- helpers/templates/getGuildTemplates.ts
- helpers/templates/getTemplate.ts
- transformers/mod.ts
- transformers/template.ts
- types/discord.ts
- types/shared.ts
This adds a template transformer. Also this fixes incorrect type definitions regarding templates.
Breaking Change: The previously called `Template` interface which was used for creating templates has been renamed to `CreateTemplate`
Closes: #2097
> feat(helpers,types)!: add guild template transformer

- transformers/auditlogEntry.ts
- types/discord.ts
This adds the `image_hash` audit log change key which is being used when a guild scheduled event cover image gets updated.
Reference: https://github.com/discord/discord-api-docs/pull/4707
Closes: #2138
> feat(types): add `image_hash` audit log change key

- transformers/toggles/role.ts
In the role tags discord sends a `premium_subscriber` field. It seems that this has been forgotten to add.
Reference: https://discord.com/developers/docs/topics/permissions#role-object-role-tags-structure
Closes: #2140
> feat(types): add `premiumSubscriber` to `RoleToggles`

- template/bigbot/src/rest/mod.ts
There where instances where some requests crashed the rest process. I found that checking for a body pretty much fixed it. 
There is probably a better way to do this, please improve this if you have an idea :)
> fix: prevent crashing the rest process

- .github/workflows/test.yml
- helpers/channels/getChannel.ts
- site/docs/general/migrating.md
- template/bigbot/src/bot/types/command.ts
- testss/channels/deleteWithReason.test.ts
- testss/channels/deleteWithoutReason.test.ts
- testss/deps.ts
- testss/mod.ts
- testss/utils.ts
- transformers/channel.ts
- transformers/guild.ts
- transformers/message.ts
This PR introduces a new style of doing unit tests. Since our library is oriented towards big bot developers, our unit tests should also be oriented towards using proxies. This PR introduces a proxy REST and adds the first test to showcase that this design works.
The general idea of the new design is to eliminate the need of having startBot() and leaking ops in tests. This will allow us to run all our tests in parallel as well as check any leaks. Each test will be entirely standalone and run in entirely separate contexts.
**Main Concerns:**
- Since this no longer uses the internal REST code, we need to remember to update the PROXY when REST code undergoes major changes.
- Currently this PR does not introduce the Gateway PROXY. I am still unsure how to implement that at this time. …
> Proxy delete channel tests

- README.md
- template/bigbot/README.md
- template/bigbot/configs.ts
- template/bigbot/deno.json
- template/bigbot/makefile
- template/bigbot/src/gateway/mod.ts
You might want to cherry pick, and remove the reference to `create-discordeno-bot` if you would like. However, the main change here is adding support for deno tasks for the bigbot template. These changes work as of deno v1.20.3.
> Fixing the BigBot Template

- transformers/applicationCommandOption.ts
`required` is optional for options as stated in [doc](https://discord.com/developers/docs/interactions/application-commands#application-command-object-application-command-option-structure)
> fix: made `required` optional for application command option interface

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
- bot.ts
- gateway/README.md
- gateway/gatewayManager.ts
- plugins/fileloader/README.md
- site/docs/big-bot-guide/events.md
- site/docs/big-bot-guide/gateway.md
- site/docs/general/getting-started.md
- site/docs/general/migrating.md
- tests/mod.ts
- testss/mod.ts
- types/shared.ts
This changes the calculation of intents to be manual to the dev.
This is to improve overall consistency of our code base, also it is not a big drawback for users since intents are usually done once and then never (seldom) touched again.
> refactor(.github,README,gateway,plugins/fileloader,tests,types)!: make intent calculation manual

- util/constants.ts
This PR fixes an endpoint with a wrong URL
https://discord.com/developers/docs/resources/user#get-current-user-guilds
> fix: wrong USER_GUILDS url

- helpers/members/avatarUrl.ts
- transformers/component.ts
https://discord.com/developers/docs/reference#image-formatting
Image size can be any power of two between 16 and 4096.
> Image Size 4096

- helpers/guilds/getAuditLogs.ts
- types/discord.ts
closes #2407 
upstream https://github.com/discord/discord-api-docs/commit/b3a575c8613b848ee4f5f91c1c297dd45ef5fca2
> add application_commands to audit log structure

- helpers/messages/getReactions.ts
[util/routes.ts](https://github.com/discordeno/discordeno/blob/aca0e3cf1b74db1b39ff30897ae18ab198aab18b/util/routes.ts#L74) already takes care of URI encoding the emoji in the request.  This PR removes the extra URI encode to let the getReactions function work.
This fix was discussed on discord [here](https://discord.com/channels/785384884197392384/1016114488958791751/1016114491953532968).
> Fixes getReations by removing the double URI encode

- helpers/messages/reactions/getReactions.ts
- util/constants.ts
Looks like the fix in [my previous PR](https://github.com/discordeno/discordeno/pull/2438) got lost in a reorganization done right before the v14 release.  This PR puts the fix back.
> Fixes getReactions again.

- types/discord.ts
Closes: #2453 
Upstream: https://github.com/discord/discord-api-docs/commit/a710ec3ba17ac71751221315f4abf66d4711f938
> Add note about missing webhook following source

- helpers/messages/sendMessage.ts
- plugins/validations/src/messages/sendMessage.ts
When creating a message, apps must provide a value for **at least one of** `content`, `embeds`, `sticker_ids`, `components`, or `files[n]`. https://discord.com/developers/docs/resources/channel#create-message-jsonform-params
Closes: #2454 
Upstream: https://github.com/discord/discord-api-docs/commit/e5bde9a18761e54c2cf4f1e090f6376b9d8e03f1
> plugins/validations: sendMessage at least one

- types/discord.ts
When the connection has a corresponding thrid party OAuth2 token `two_way_link` will be set to `true`.
Reference: https://github.com/discordeno/discordeno/issues/2479
Closes: #2479
> feat(types)!: add `two_way_link` to `DiscordConnection`

- transformers/component.ts
- transformers/reverse/component.ts
- types/discord.ts
The component transformer and the reverse transformer don't parse the min and max length of a text input component.
This PR fixed this problem.
> fix(transformers): add min and max length to text input components

- transformers/component.ts
- transformers/reverse/component.ts
- types/discord.ts
the `required` field didn't get transformed to DiscordComponent
> fix(transformers): transform required field for InputText

- rest/runMethod.ts
Hi, 
I had some problems with a (nestjs-)fastify proxy that wasn't fine with sending no body but a content-type header.
This should fix the issue and shouldn't affect other bots.
> fix(rest): only send Content-Type header to proxy if body content is sent

- transformers/toggles/emoji.ts
- transformers/toggles/guild.ts
- transformers/toggles/member.ts
- transformers/toggles/role.ts
- transformers/toggles/user.ts
- transformers/toggles/voice.ts
Currently there's a way to convert toggles to bigint (like `new GuildToggles(guild).bitfield`) but not a way to reverse it (converting bitfield to toggles), this PR adds support for that
> feat: allow bigint or number to be passed in toggles classes too and not only the object

- packages/embeds/mod.ts
Close #2541 
Cause by using helpers before helpers initialize 
Only affected ESM, cjs not affected
> fix: ReferenceError: publishMessage is not defined

- plugins/permissions/src/permissions.ts
After testing the permissions plugin I stumbled upon what might be an oversight. `bot.members.get()` won't work sometimes as multiple members in this collection may have the same ID. This new code seems to work better from my testing with one of my bots, but I have not done rigorous testing.
> calculateBasePermissions may not correctly retrieve cached members

- helpers/channels/createChannel.ts
- helpers/channels/editChannel.ts
- types/discord.ts
- types/shared.ts
types: add SortOrderTypes and default_sort_order to DiscordChannel
helpers: add defaultSortOrder to createChannel and editChannel options
closes: #2518 
upstream: https://github.com/discord/discord-api-docs/commit/d81f425adff2fa0a330f648aece421d085479932
docs:
[create channel](https://discord.com/developers/docs/resources/guild#create-guild-channel-json-params)
[edit channel](https://discord.com/developers/docs/resources/channel#modify-channel-json-params-guild-channel)
[discord channel](https://discord.com/developers/docs/resources/channel#channel-object-channel-structure)
[sort order types](https://discord.com/developers/docs/resources/channel#channel-object-sort-order-types)
> types: add SortOrderTypes and default_sort_order to DiscordChannel, helpers: add defaultSortOrder to createChannel and editChannel options

- helpers/channels/createChannel.ts
Closes: #2513 
Upstream: https://github.com/discord/discord-api-docs/commit/c2f74223c6f00d48a678bcd75892ff43ea5a2ddc
Docs: 
[Create Guild Channel](https://discord.com/developers/docs/resources/guild#create-guild-channel-json-params)
[Default Reaction](https://discord.com/developers/docs/resources/channel#default-reaction-object-default-reaction-structure)
[Forum Tag](https://discord.com/developers/docs/resources/channel#forum-tag-object-forum-tag-structure)
> helpers: Add missing properties for create guild channel

- helpers/messages/sendMessage.ts
- plugins/validations/src/components.ts
- types/discordeno.ts
- types/shared.ts
Closes: #2523 
Upstream: https://github.com/discord/discord-api-docs/commit/4db171cc910f519470cb19ab650aa0eeeaca5b11
Docs:
[Component Types](https://discord.com/developers/docs/interactions/message-components#component-object-component-types)
[Select Menu](https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-structure)
> add new select menu components

- helpers/channels/editChannel.ts
- plugins/permissions/src/channels/editChannel.ts
Closes: #2570 
Upstream: https://github.com/discord/discord-api-docs/commit/ebd68c8088d37d6082ab133ff4698c4c97f379b3
Docs:
[applied_tags: Edit Channel (Thread)](https://discord.com/developers/docs/resources/channel#modify-channel-json-params-thread)
[available_tags: Edit Channel (Guild Channel)](https://discord.com/developers/docs/resources/channel#modify-channel-json-params-guild-channel)
> helpers: add appliedTags to editHelper options

- helpers/guilds/events/editScheduledEvent.ts
As the discord docs, https://discord.com/developers/docs/resources/guild-scheduled-event#guild-scheduled-event-object-field-requirements-by-entity-type said beside ENTITY TYPE is EXTERNAL, it should be null but it was undefined before. This should fix the integration test failing
Close #2592
> [helper] Fix entity metadata

- packages/types/src/discord.ts
- packages/types/src/discordeno.ts
In the [docs](https://discord.com/developers/docs/interactions/message-components#button-object-button-structure), label is an optional property but it's not in discordeno, this PR fixes that issue
> fix: typing of button component label to be optional

- packages/utils/src/casing.ts
Sometimes regex replaces can be pretty slow. Therefore I suggest to add a more performant converter function. 
This PR makes the related part of the code ~3.3 times faster.
@H01001000 Compared the old and new `camelize` functions on a `GUILD_CREATE` payload, the improvement was ~2.2x.
> perf(utils): optimize snake to camel case conversion

- plugins/fileloader/mod.ts
When working with multiple directories that have many sub-directories all with multiple files that need to be loaded, it is possible for the `fileLoader` to be called prematurely as shown here:
*The imports as they would be written is logged directly from the `fileLoader` function while the individual paths are logged from the `importDirectory` function*
By awaiting the original call `importDirectory` we can wait for all recursive calls to finish running before calling `fileLoader`.
Test results locally:
Testing with multiple sub-directories that broke originally:
You can read more in the [Discord thread titled _"Fileloader having issues with directories."_](https://discord.com/channels/785384884197392384/1071701118821875763).
> fix: await importDirectory call

- packages/bot/tests/e2e/resetguilds.spec.ts
fix type error in ci
```
Error: @discordeno/bot:test:test-type: tests/e2e/resetguilds.spec.ts(20,36): error TS2345: Argument of type 'DiscordenoShard' is not assignable to parameter of type 'number'.
Error: @discordeno/bot:test:test-type: tests/e2e/resetguilds.spec.ts(25,59): error TS2345: Argument of type 'DiscordenoShard' is not assignable to parameter of type 'number'.```
> test(bot): fix test type

- packages/types/src/discordeno.ts
Previously the maximum file size has been documented as 500 KB. This has now been updated to 512 KB.
Closes: https://github.com/discordeno/discordeno/issues/2875
> docs(types): update `CreateGuildStickerOptions` file size

- packages/rest/src/types.ts
Closes: https://github.com/discordeno/discordeno/issues/2928
> docs(rest): webhook names cannot contain 'discord'

- packages/benchmark/src/benchmarks/transformers.ts
- packages/benchmark/src/utils/memoryBenchmark.ts
- packages/bot/src/transformers.ts
- packages/bot/src/transformers/message.ts
- packages/bot/src/transformers/toggles/ToggleBitfield.ts
- packages/bot/src/typings.ts
- packages/bot/src/utils.ts
Changes From This Style:
- `1:1 shape`
- `message.author` now exists
- Other things similar to this are now available. 
- `desiredProps`
- This now is set by default so that no props are cached by default. Users need to opt-into each prop they want. This makes it similar to intents which will help prevent devs from using unneeded memory.
- This also allows a much simpler solution to remove properties as opposed to have to override an the entire transformer just to remove `topic` from channel.
- `Customizers`
- This is the a handler for each transformer which users can override to easily add new properties or customize something without major overriding. For example, say a user wants to add a new property on `message` like `args`. A customizer can be written:
```ts …
```
> fix(transformers): message transformer using different style

- packages/rest/src/manager.ts
- packages/rest/src/types.ts
- packages/rest/tests/e2e/guild.spec.ts
- packages/types/src/discordeno.ts
Improved the consistency by separating the audit log reason to an optional function parameter. Also added support for 100% documented reason endpoints.
> fix(rest, types)!: support auditlog reason

- packages/rest/src/manager.ts
- packages/rest/src/types.ts
Currently some interaction handling uses `sendRequest` directly. This adds the `runThroughQueue` option, which prevents the request to be handled by a queue effectively giving the same effect as using `sendRequest` directly. This prevents code repetition and supports future endpoints which might not have a rate limit too.
Further more all interaction related endpoints have now been set to not send the bots authorization header.
> refactor(rest): interaction handling

- packages/bot/src/bot.ts
- packages/rest/src/manager.ts
- packages/rest/src/types.ts
- packages/rest/tests/unit/manager.spec.ts
This is in favour for interaction only bots, which still need rest but cannot provide a valid bot token. If you want to use rest for your normal bot it should be your own responsibility to pass a valid token.
Further more `applicationId` is now a required property since we cannot extract the id from the token anymore.
> refactor(rest)!: remove falsy token check

- packages/rest/src/manager.ts
- packages/rest/src/queue.ts
- packages/rest/src/types.ts
- Removed `url` in favour of `route`. This change will effectively remove a bunch of unnecessary checks from dd. Also this changes how rest proxies have to pass the route to the `makeRequest` function. Since it will just require you to pass `req.route + req.query` it is an improvement compared to `rest.baseUrl + req.route + req.query`.
- Introduced `HttpResponseCodes` an internal enum to remove magic numbers.
- Improved the rate limted response handling. Made it simpler.
- Removed unnecessary `JSON.stringify(await result.json())` since `await result.text()` does effectively the same.
- Changed the anti memor leak `response.json()` to `response.arrayBuffer()` since latter does not do any additional processing.
> refactor(rest)!: improve `sendRequest`

- packages/rest/src/invalidBucket.ts
- packages/rest/tests/e2e/automod.spec.ts
- packages/rest/tests/e2e/emoji.spec.ts
- packages/rest/tests/e2e/guild.spec.ts
- packages/rest/tests/e2e/member.spec.ts
- packages/rest/tests/e2e/message.spec.ts
- packages/rest/tests/e2e/role.spec.ts
- packages/rest/tests/e2e/stickers.spec.ts
- packages/rest/tests/e2e/user.spec.ts
- packages/rest/tests/e2e/webhook.spec.ts
Instead of using timeouts we should aim to use a lazy bucket system.
Further more variables have been renamed to add more clarity.
> refactor(rest)!: make invalid bucket lazy

- packages/bot/src/transformers/interaction.ts
https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-object-interaction-data
shows that there exists a type property on the data
> feat(bot): add `Interaction.data.type` for Command interactions

- packages/types/src/discord.ts
https://discord.com/developers/docs/interactions/application-commands#create-global-application-command
states that description is optional. This is when using message commands for example
> fix(types): `DiscordCreateApplicationCommand.description` is optional

- website/src/styling/index.ts
Minor change to the header's before element's `z-index`
> fix(website): header gradient shadow overlapping navbar

- packages/bot/src/transformers/interaction.ts
- [Breaking] `respond`'s `response` now takes `InteractionCallbackData`
- `respond`'s `options` is now optional
- Added `edit`, `defer` and `delete`
> feat(bot): add more helper functions to `BaseInteraction`

- packages/bot/src/transformers/interaction.ts
- `Interaction.shownModal` was useless since it does not carry over to the modal's interaction
- Block modal response to a modal interaction
- Allow only autocomplete response for an autocomplete interaction
> fix(bot): Fix `BaseInteraction.respond` & add response validation

- packages/gateway/src/manager.ts
Use `options.totalShards - 1` if `options.lastShardId` doesn't exist, which if not exists, use `options.connection.shards - 1`
> fix(gateway): lastShardId

- packages/bot/src/transformers/component.ts
- packages/bot/src/transformers/reverse/component.ts
- packages/bot/src/typings.ts
- packages/types/src/discord.ts
- packages/types/src/discordeno.ts
https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-structure
> feat(bot,types): Add `channel_types` prop to channel select menu

- packages/rest/src/manager.ts
- packages/rest/tests/e2e/message.spec.ts
- packages/types/src/discordeno.ts
This fixes `editMessage` not sending new files. I also updated the e2e message spec test.
> fix(rest): add missing files for editMessage

- packages/rest/src/manager.ts
Maybe it needs to be done here too? 
https://github.com/Yaikava/discordeno/blob/33d260e2bb583eaa779ff3a0b3762a3c819dabe1/packages/rest/src/manager.ts#L185
This  should probably be looked into too, but I do not really know.
https://discord.com/channels/785384884197392384/1123611467934085190/1123955065674281050
> 🐛 - fix: snakelize json when files are used

- packages/bot/src/transformers/auditLogEntry.ts
- packages/bot/src/transformers/reverse/auditLogEntry.ts
This fixes audit log entries which contain changes to guild icon, webhook icon etc. The problem was that hashes were incorrectly interpreted as snowflake IDs.
> fix(bot): Transform hashes correctly

- packages/gateway/src/Shard.ts
1.35.2 removed `window` from node's `globalThis` (https://github.com/denoland/deno/pull/19307)
> fix(gateway): update deno detection

- packages/bot/src/bot.ts
- packages/gateway/src/manager.ts
* Fix for the `bot.start()` method where the `if (!options.gateway?.connection)` always return false since the create `createGatewayManager` function created the value if non-existing.
* Add checks to try to avoid changing user options when doing the fetching
> Bug(gateway) Fix fetch of discord gateway session information

- packages/rest/src/manager.ts
When you use proxy rest, the request object is already converted to Discord format in the bot side, and then sent to the proxy rest, this means it runs `changeToDiscordFormat()` again, which means the fields `allow`, `deny`, `permissions` and `defaultMemberPermissions` will have a string instead of a permission string array in the rest side. When a string is passed to `calculateBits()`, it's not processing and is freezing the request, causing it to timeout. This PR fixes that issue but we might need to think of a better approach overall to prevent running `changeToDiscordFormat()` twice (once in bot side, once in rest proxy side)
> fix(rest): failing to convert to Discord format for permission related fields in object in changeToDiscordFormat() with proxy rest

- packages/rest/src/manager.ts
Fix bug where the only way to not attach the REST authorization header was setting unauthorized to false. Now the name and behavior match
> fix(rest): invert unauthorized check

- packages/types/src/discordeno.ts
Reported in #3119, this fixes the typing for `communicationDisabledUntil`.
> fix(types): change communicationDisabledUntil to string or null

- packages/rest/src/manager.ts
Fix `TypeError: Do not know how to serialize a BigInt` from `JSON.stringify()` when the options contains both a file, so the body requires to be a form data, and has a body with a BigInt somewhere in the body.
> Fix(rest) Fix error when serializing payload with a BigInt

- packages/rest/src/manager.ts
Once globally ratelimited, it's supposed to wait until `retryAfter` but instead of passing that to the `setTimeout`, a timestamp is passed, this PR fixes that issue
> fix: bug with rest manager passing a timestamp instead of milliseconds in setTimeout

- packages/types/src/camel.ts
- packages/types/src/discord.ts
- packages/types/src/discordeno.ts
Add the support for Select Menu (type 5[^5] 6[^6] 7[^7] 8[^8]) according to discord/discord-api-docs#6442
[^5]: User select menu
[^6]: Role select menu
[^7]: Mentionable select menu
[^8]: Channel select menu
> Add default_values support for SelectMenu

- packages/utils/src/builders.ts
- packages/utils/src/builders/embeds.ts
- packages/utils/src/index.ts
- packages/utils/tests/builders.spec.ts
This is a PR implementing the embed builder from #3124, based on PR #2931.
- This is only embed builders, others will come later.
- Uses DD Discord interfaces and uses `Omit` to pull out any key we use as required.
- Uses [ECMAScript private getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#private_methods) to get the current embed instead of a method.
- Simplified code a bit, the modifying the getter directly vs setting new variable and modifying. This is more preference.
- Using `set` before method names to make it more descriptive of intent of method
- Custom `EmbedBuilderError`
- Use spread operations where possible.
- Optional `validate` method that check all embeds to ensure they're in the [documented embed …
> feat(utils): add embed builder

- packages/gateway/src/Shard.ts
- packages/gateway/src/manager.ts
- packages/gateway/src/types.ts
Allow for the gateway manager to send the messages to a non-in-memory shard without overriding all methods that send messages to shards in the gateway manager
TODO:
> feat: allow for custom function to send the payload to shards

- packages/bot/src/helpers.ts
- packages/rest/src/manager.ts
- packages/rest/src/types.ts
- packages/types/src/discord.ts
Following discord/discord-api-docs#6356, now the `exchangeToken` and `revokeToken` use the Basic + Base64 of `CLIENT_ID:CLIENT_SECRET` instead of passing them in the body.
> fix(rest)!: Update OAuth2 to use the Basic authentication

- packages/rest/src/manager.ts
- packages/rest/src/types.ts
Add of an option on the `CreateRestManagerOptions.proxy` object to specify a different header from `authorization` to allow for non-generable headers (eg. `Bot <bot token>`) to be sent to the rest proxy for situation like OAuth2 required endpoint using Bearer tokens, and for the exchange and revocation of Bearer tokens using a Basic authentication.
The `CreateRestManagerOptions.proxy.authorizationHeader` defaults to `authorization` to keep compatibility with the alredy exiting rest proxies
> feat(rest): Add option for the header of authorization on rest proxy

- packages/utils/src/bucket.ts
This PR fixes 2 bugs with the `LeakyBucket` implementation
- When the `processQueue` is invoked mark it as processing to prevent the loop inside it from being run more than 1 time at once.
- When the timeout is scheduled to be run after the `while` loop resumes execution sleep 1 more second and prevent it to run endlessly
> fix(utils): Mark bucket as in processing, delay if no requests available

- .vscode/settings.json
Using an array for code actions (introduced in 1.44, 2020-04-08) allows for explicitly say the order of the actions. The current approach does not guarantee that the actions are runner in order, and it seems that in `1.85-insider` it is causing problems
> fix(vscode): Explicitly sort the code actions

- packages/bot/src/handlers/guilds/GUILD_DELETE.ts
Currently right now you need both `guildDelete` and `guildUnavailable` events defined if you want to process either event. This PR makes it so you only need the event you want to handle defined, in case you don't want to have to process unavailable events. 
This has the same amount of logic checks as before.
> feat: only require one guild delete event

- packages/benchmark/package.json
- packages/bot/package.json
- packages/discordeno/package.json
- packages/gateway/package.json
- packages/rest/package.json
This PR fixes few packages's require use .js extension instead .cjs extension, during cjs rewrite,
> fix: cjs extensions for require

- packages/utils/src/images.ts
Add the missing image url function in the utils package with a few exceptions: 
- Achievement Icon and Store Page Asset: Part of the Game SDK
- Guild Member Banner: Doesn't have documented the banner asset hash on the Guild Member
- User Avatar Decoration: Already included in #3257
fixes #2677
> feat(utils): Add missing image url function

- .github/CODEOWNERS
Was thinking about looking at the other sections too. Wanted to ask @H01001000 on that though.
Before we can merge though, the @discordeno/core team may need a permission update so it has write access? There's an error with the core team that makes it invalid. Not sure what's going on there.
> feat: add Discordeno team to codeowners

- .github/workflows/labeler.yml
change labeler that it only label w unverified when pr is open or reopen, so editing the title or commiting will not affect
> ci: fix-labeler

- packages/bot/src/helpers.ts
- packages/bot/src/transformers/interaction.ts
Currently the helper methods in the interaction object (`respond`, `defer`, `edit` and `delete`) use the rest methods causing the objects to be returned as the Camelized variants of the discord raw object instead of the discordeno transformed value.
This pr changes these methods to use the helper methods and also updates their comment to specify what options they use (for an easier time with desired proprieties and those methods)
*Also removed a non-necessary null check in the editOriginalInteractionResponse as it always respond with the message object just like the webhooks methods*
> fix(bot): Use helpers in interaction methods

- packages/rest/src/manager.ts
- packages/rest/src/types.ts
The getGuilds rest manager method assumed that the token was always a bearer token and it required it to be present. The method now does not require the token as a required parameter and checks for it when sending the request
> fix(rest): Add support for getGuilds with bot token

- packages/types/src/discordeno.ts
doc: [`options` is [...] unavailable for all other select menu components.](https://discord.com/developers/docs/interactions/message-components#select-menu-object-select-menu-structure:~:text=*-,options,\)%2C%20and%20unavailable%20for%20all%20other%20select%20menu%20components,-.)
> fix(types): rm `options` from `SelectMenuUsersAndRolesComponent`

- packages/rest/src/routes.ts
This removes `has_message` from the forum route which causes a bug when creating a thread in a forum channel that requires a root level `content` even though the message content is contained inside a `message` object.
> fix(rest): remove has_message from forum route

- packages/bot/src/transformers/interaction.ts
The current helpers for the interaction transformer are pretty difficult to use especially with `MessageComponent` interaction if you want to do a type 7 (`UPDATE_MESSAGE`) response, as currently you need to first defer the interaction to create a type 6 (`DEFERRED_UPDATE_MESSAGE`) and then update the original interaction response to edit the message from where the interaction originated from.
This pr also adds the `messageId` argument to edit to edit a followup response as that was missing, it also adds the `premiumRequired` helper to send type 10 (`PREMIUM_REQUIRED`) responses.
closes #3455
> feat(bot)!: update interaction helpers

- packages/benchmark/src/benchmarks/rest.ts
- packages/bot/src/bot.ts
- packages/bot/src/handlers/members/GUILD_MEMBERS_CHUNK.ts
- packages/gateway/src/manager.ts
- packages/rest/src/manager.ts
- packages/rest/src/types.ts
- packages/rest/tests/unit/manager.spec.ts
This PR seeks to improve the interface of the `createBot()` function by doing the following:
- `options.events` is now optional (previously the user had to pass in an empty object).
- `options.gateway.token` is now also optional since it can be inherited from `options.token`.
- `options.gateway.cache.requestMembers.pending` is now optional given that it gets set to an empty `Collection` object anyway by `createGatewayManager()`.
> refactor(bot, gateway, rest)!: Improve the interface of the `createBot()` function.

- packages/rest/src/manager.ts
Currently the errors that the REST manager produces are very confusing and require a lot of guessing to what is actually the user invoked function that is causing the error. This is even worse if discord responded with a body that is a very generic error like the 404 errors, or with Bun where, due to a bug(?) it simply displays the red text `Error` with no details in any way.
This pull request modifies how the rest rejects the promise created by `makeRequest` function by using an error object along with the normal object, below are the before and after of the errors.
One more thing we could do is pass the full `fetch` `Request` object inside the error for the user, I'm not convinced because then the full request object will get converted to string into the console on an error
*without …
> feat(rest): Improve rest errors

- docker-apps/rest-passthrough/package.json
- docker-apps/rest-passthrough/src/fastify.ts
- docker-apps/rest-passthrough/src/server.ts
- docker-apps/rest-passthrough/yarn.lock
Currently when you send a request to the rest proxy that involves uploading a file it will fail as fastify does not know how to handle the multi-part body that it receives. This pr adds the `@fastify/multipart` package to handle this and a function to build the FormData object to give to `@discordeno/bot`.
This pr also bumps the version of `@discordeno/rest` in the proxy to the latest on npm due to bugs when testing the code
closes #3354
> fix(rest-proxy): check for multi-part bodies

- scripts/fixCjsExtension.js
Currently the script uses a RegExP to change all the `.js` references to `.cjs` to avoid runtime errors as since we have `"type": "module"` in our package.json all the `.js` files are getting interpreted as ESModules and we need to use the `.cjs` extension for CommonJS. The script just checked for the presence of `.js` anywhere in the code and replaced with `.cjs` but this caused errors in the REST package as the `Response` object that `fetch()` returns has a `.json` method to get the JSON body but `.json` starting with `.js` was being matched by the RegExP and was creating unexpected runtime errors. This pr adds a RegEx Negative LookAhead to make sure we aren't replacing any `.json` instance.
> fix(build): Fix CJS extension script to avoid replacing .json

- packages/types/src/discord.ts
Adds the Bungie connection to the `DiscordConnectionServiceType` enum
closes #3524
> feat(types): Add bungie discord connection

- packages/rest/src/types.ts
This updates the comment with the updated required permissions needed when pruning the members in a guild. This now takes the `MANAGE_GUILD` permissions other then the `KICK_MEMBERS` according to new commits in discord/discord-api-docs (#3497)
closes #3497
> feat(rest): Update comment for permissions needed when pruning members

- packages/bot/src/helpers.ts
- packages/rest/src/manager.ts
- packages/rest/src/routes.ts
- packages/rest/src/types.ts
- packages/rest/src/typings/routes.ts
- packages/types/src/camel.ts
- packages/types/src/discord.ts
- packages/types/src/discordeno.ts
Add support for the bulk ban rest endpoint.
closes #3518 (reference: https://github.com/discord/discord-api-docs/pull/6720)
> feat(types,rest,bot): Add bulk ban support

- scripts/bumpVersionByCommit.js
Currently the /scripts/bumpVersionByCommit.js when it needs to bump the dependencies of a package to publish it checks that the dependency version is the same as the package version. This now creates an issue because some packages are classified as beta while other as alpha making the NPM release impossibile to install (see https://github.com/discordeno/discordeno/issues/3519#issuecomment-2082112108).
This pr changes the script to instead use the `@discordeno` npm scope to check if it needs to update the version for the package dependency.
> fix: bump script ignoring some `@discordeno` deps

- packages/gateway/src/Shard.ts
Currently we add to the debug logs for the shards the bot token when resume is called. In the rest package we do censor it with "tokenhere" while still showing the HTTP header, however in this situation there isn't the need to show what token is in use and it is better to not leak the bot token in a log file or something like that
> fix(gateway): Remove bot token from the shard debug logs

- packages/types/src/shared.ts
- packages/utils/src/images.ts
Use media.discordapp.net for gif stickers, cdn.discordapp.com returns a 404 for gif stickers
Add Gif to StickerFromatTypes as it was missing
Upstream: [discord/discord-api-docs#6831](https://github.com/discord/discord-api-docs/pull/6831)
fixes #3576
> fix(utils): Use media.discordapp.net for gif stickers

- packages/types/src/discord.ts
Add domain connection service type to the DiscordConnectionServiceType enum
Upstream: [discord/discord-api-docs#6395](https://github.com/discord/discord-api-docs/pull/6395)
fixes #3585
> feat(types): Add domain connection service type

- packages/rest/src/manager.ts
- packages/rest/src/types.ts
Add a reason param to followAnnouncement, this will specify the X-Audit-Log-Reason header and it will be logged in the Discord Audit log
Upstream: [discord/discord-api-docs#6559](https://github.com/discord/discord-api-docs/pull/6559)
fixes #3587
> feat(rest): Add reason to followAnnouncement

- packages/rest/src/manager.ts
- packages/rest/src/types.ts
Add `botBannerURL` to edit current bot banner
Upstream: [discord/discord-api-docs#6710](https://github.com/discord/discord-api-docs/pull/6710)
fixes #3596
> feat(rest): Add `botBannerURL` to edit current bot banner

- packages/types/src/discord.ts
- packages/types/src/discordeno.ts
Update and clarify when the options for options are valid given the type of the command/option
Upstream: [discord/discord-api-docs#6177](https://github.com/discord/discord-api-docs/pull/6177)
fixes #3599
> docs(types): Update some documentation of the options for slash commands

- packages/types/src/shared.ts
Add `PurchaseNotification` (44) on `MessageTypes`
- Upstream: https://github.com/discord/discord-api-docs/pull/6927
- fixes #3654
> feat(types): `PurchaseNotification` message type

- packages/types/src/discordeno.ts
Document default values for `duration` and `allowMultiselect` `CreatePoll`
- Upstream: https://github.com/discord/discord-api-docs/pull/6968
- fixes: #3700
- depends on: #3694
This pr depends on #3694 since changing the default to 24 but still having "up to 7 days" would be **very** confusing
> feat(types); Update default values for poll creation

- packages/bot/src/bot.ts
- packages/bot/src/handlers/emojis/GUILD_EMOJIS_UPDATE.ts
Currently we use `Collection<bigint, DiscordEmoji>` for the `guildEmojisUpdate` event, however there is not reason (afaik) to use `DiscordEmoji` instead of the transformed object `Emoji`
Fixes: #3703 
> [!WARNING]
> This is breaking because the `DiscordEmoji` and the `Emoji` type are incompatible, this may result in Typescript type errors
> fix(bot)!: Use `bot.transformers.emoji` in `handleGuildEmojisUpdate`

- packages/utils/src/oauth2.ts
Currently the `createOAuth2Link` function uses a space character to join the scopes provided, this does work, however it creates an issue where if you don't pass the resulting URL in something like the `URL` constructor the space can give issues when using. For example, it makes discord error when used as the url for a link button
> fix(utils): Use '%20' instead of ' ' for joining scopes

- packages/bot/src/bot.ts
- packages/bot/src/handlers/guilds/GUILD_STICKERS_UPDATE.ts
Currently there is no way to access the `guildId` on the `guildStickersUpdate` event if the events sends an empty array of stickers
Fixes: #3702 
> [!WARNING]
> This is a breaking change since it changes the argument to `guildStickersUpdate` to be a payload object with the `guildId` and the stickers as proprieties on it
> fix(bot)!: Add `guildId` to `guildStickersUpdate` event

- packages/bot/src/transformers.ts
- packages/bot/src/transformers/attachment.ts
- packages/types/src/discord.ts
Add attachment titles
- Upstream: https://github.com/discord/discord-api-docs/pull/6945
- fixes #3688
> feat(bot,types): Add attachment titles

- packages/bot/src/transformers/interaction.ts
- packages/bot/src/transformers/message.ts
- packages/bot/src/transformers/sku.ts
- packages/bot/src/typings.ts
- packages/types/src/discord.ts
- packages/types/src/discordeno.ts
- packages/types/src/shared.ts
Add the enum for `ActivityTypes`. Rename and move enums for `MessageFlags` and `SkuFlags`
> [!NOTE]
> This pr does not remove these types from the objects. Currently some object still use `MessageFlags` and `SkuFlags`
> [!WARNING]
> This is a breaking change as before `MessageFlags` was called `DiscordMessageFlag` and `SkuFlags` was called `DiscordSkuFlag`.
> The prefix `Discord` was dropped for consistency with other flag enums (`ChannelFlags`, `RoleFlags`, `UserFlags`, ...)
> feat(types)!: Add flags enums

- packages/bot/src/transformers.ts
- packages/bot/src/transformers/toggles/guild.ts
- packages/types/src/shared.ts
Followup to #3705, turns out i got VERY wrong the type (i put a `keyof` instead of `[number]`).
Also i have checked all the features we have and some where missing so they got added
> [!WARNING]
> This is breaking for 2 reasons:
> 1. I have removed the `features` desired propreities as it was useless
> 1. the `monetizationEnabled` toggle was renamed to the actual name of the feature (`creatorMonetizableProvisional`)
> fix(bot)!: Guild features type

- packages/bot/src/transformers/toggles/Permissions.ts
- packages/types/src/shared.ts
- packages/utils/src/permissions.ts
Discord is pretty close to the Number.MAX_SAFE_INTEGER (around 1 << 53, with 1 << 55 it will start truncating numbers), to avoid this we need to change to BigInt.
This pr also removes some BigInt constructor calls that are no longer necessary.
The reason this PR changes the enum to an object is because Typescript does not support bigint keys in objects, and enums are transformed into objects with also the values as keys. There are issues in the typescript repo, however they date back version 2.6
> [!WARNING]
> This is a breaking change for 2 reason:
> 1. BigInt is not compatibile with number, so if you used number it breaks
> 1. Since we needed to convert to an object now if you do `BitwisePermissionFlags[1]` it now gives undefined instead of the name of the permission
> feat(types)!: Use BigInt for permission flags

- packages/bot/src/transformers.ts
- packages/bot/src/transformers/channel.ts
Currently we name the discord propriety `default_auto_archive_duration` on `Channel` as `autoArchiveDuration`. This may be confusing for users but this PR renames the propriety as `defaultAutoArchiveDuration`.
This also adds the desired propriety for `defaultAutoArchiveDuration`, we don't remove the previous one as that is used for the thread metadata
> fix(bot)!: Rename `channel.autoArchiveDuration` to `defaultAutoArchiveDuration`

- packages/gateway/src/Shard.ts
Currently we only log the close code for the shard if the error requires re-identifying (as specified by Discord), however the `close.code` can be useful in other situations as well, so now the debug logs always include them. Also they are now included in the "Closed shard #n" info log since it run on the `default` switch case where knowing the error code may be useful
> fix(gateway): Log the `code.code` more often, incluing in the generic message

- biome.jsonc
- package.json
- packages/bot/src/transformers/toggles/member.ts
- packages/tsconfig/package.json
- website/package.json
Currently yarn and biome fight every time you install the dependencies/run the formatter.
The PRs adds the package.json to the ignore list for biome.
> [!NOTE]
> This PR includes a change to the import sorting for the member toggles as #3617 got merged while using ESLint and it didn't get updated to use biome
> fix: adapt biome formatting of package.json files to match the yarn one

- .github/workflows/e2e-test.yml
- .github/workflows/integration-test.yml
- .github/workflows/lib-check.yml
- .github/workflows/unit-test.yml
Add the `token` parameter for the `codecov/codecov-action` action.
The action has been broken since #3412 was merged as in v4 the action now requires the upload token. The PR adds the param from the secrets of the github repo
- fixes #3716
> ci: Add token parameter to codecov action

- packages/types/src/discord.ts
Add the roblox connection to the `DiscordConnectionServiceType` enum
* upstream: https://github.com/discord/discord-api-docs/pull/6995
* fixes #3753
> feat(types): Add roblox connection

- packages/rest/src/manager.ts
- packages/rest/src/queue.ts
- packages/rest/src/types.ts
Currently it is possibile for the followups to get stuck in an dead queue (that will never refresh) because of the omission of both the header and the token in the url (due to how the ratelimit buckets work)
> fix(rest): Fix followups from getting stuck in queue

- .github/workflows/benchmark.yml
- .github/workflows/docker-app-rest-passthrough.yml
- .github/workflows/e2e-test.yml
- .github/workflows/integration-test.yml
- .github/workflows/lib-check.yml
- .github/workflows/other-runtime-unit-test.yml
- .github/workflows/release.yml
- .github/workflows/site.yml
- .github/workflows/unit-test.yml
Update GitHub actions versions for especially `actions/cache` and the artifacts related ones
`actions/cache@v3` uses node16 which gets force-replaced by github with node20 (as node16 is EOL) and it gives quite a few warnings in the workflow summary
It also seems to solve the issue we had with very long time to write the cache for turborepo
> ci: Update actions versions

- .github/workflows/docker-app-rest-passthrough.yml
- docker-apps/rest-passthrough/Dockerfile
Snyk uses `null` in the severity score when the CVE doesn't have an assigned score yet. This makes the codeql/upload-sarif action fail as `null` is not a valid number
This pr also bumps the base image for the docker image from alpine 3.19 to alpine 3.20
> fix(docker): prevent snyk null in severity scores for unassigned CVEs

- packages/bot/src/helpers.ts
- packages/rest/src/manager.ts
- packages/rest/src/types.ts
- packages/types/src/camel.ts
- packages/types/src/discord.ts
The `DiscordPartialGuild` was introduced with #3114, however discord does not document explicitly what are the expected proprieties someone should expect, and generically say "Partial Guild object". So, this pr uses the `Partial<DiscordGuild>` instead.
- fixes #3755
> feat(types)!: Remove `DiscordPartialGuild`, use `Partial<DiscordGuild>`

- packages/bot/src/bot.ts
- packages/bot/src/transformers.ts
- packages/types/src/shared.ts
Add `desiredProprieties` to `createBot` and make the transformers object in `createTransformers` partial. This allows a user to provide an object with some of the props they want to be included in the transformed objects
> feat(bot): Add `desiredProperties` to createBot

- packages/discordeno/bin/discordeno.js
Currently when packaging the `discordeno` package, npm at install will not run the .js file with node but will attempt to directly run the file causing weird behavior
> fix(discordeno): Add shebang

- .github/workflows/release.yml
Add the `discordeno` package to the release workflow.
Currently we do not publish it, adding it will make it possible to test the CLI without messing with `.tgz` files
> [!NOTE]
> This will make a dev version of discordeno become the latest version.
> 
> When we will release v19 we will need to add `@<tag>` to the npm command after the package name
> feat(ci): Add discordeno to the release workflow

- packages/gateway/src/Shard.ts
Currently when we call `send` in a shard we check if the shard is online, and if it isn't the payload is queued for when it is online, however we do not clear the promises resolve callbacks, keeping iterating on useless callback that won't do anything as the promise already resolved.
Also, we currently use the `.map` method that will return a new array with the results resulting in a waste of memory as those arrays are also never used, so `.forEach` is a better method to use for this use-case
> fix(gateway): Clear `offlineSendQueue` after resolving all the promises

- packages/types/src/shared.ts
Rename the `Game` activity type to `Playing`
- upstream: https://github.com/discord/discord-api-docs/pull/7033
- fixes #3804
> feat(types)!: Rename `Game` activity type to `Playing`

- packages/bot/src/bot.ts
- packages/gateway/src/manager.ts
Currently the resharding
- Will throw an error if you don't provide a `getSessionInfo`, while we can provide a fallback value if you use `createBot` from `@discordeno/bot`
- Will attempt to reshard regardless of the % of capacity (the formula is bugged)
- Will make `gateway.resharding.shards` and `gateway.shards` be the same collections, create issues at a later point
TODO:
(@AwesomeStickz)
> fix(bot,gateway): Fix (some) resharding bugs 

- turbo.json
Turbo in v2 does not pass down the environment variables unless manually specified (by default), so the E2E run is failing for the missing environment variable for the `DISCORD_TOKEN` and `UNIT_TEST_GUILD_ID`.
> [!NOTE]
> CI has also add the env for `PROXY_REST_SECRET` and `PROXY_REST_URL`, however they are not used, so i didn't add them to the turborepo configuration
> fix(ci): Add env to `test:e2e` turbo task

- packages/gateway/src/Shard.ts
Currently our debug logs in `startHeartbeating` consists of `[Gateway] Start Heartbeating Shard #<id>` and then a letter based on the order of the log call.
This pr replaces these logs with more clearer versions of these logs to help with the understanding of these logs without having a direct reference on the code on the side as remembering what each letter means is really difficult.
Also, this removes a few log calls as they were right before/after another one with no real use for both of them
> fix(gateway): Make heartbeat logging clearer

- packages/bot/src/bot.ts
Currently our `bot.events.messageUpdate` and `bot.events.presenceUpdate` accepts 2 parameters, the updated message/presence and the old message/presence, however discord doesn't give the old message/presence, so this removes it as it is never called with that second parameter set to something
> [!WARNING]
> This is breaking because it is changing the `messageUpdate` and `presenceUpdate` events function signature
> fix(bot)!: Remove old unprovided params from event params

- packages/rest/src/manager.ts
Currently for `nameLocalizations`, `descriptionLocalizations` and some others, we have a special behavior. In the specific case of `nameLocalizations` and `descriptionLocalizations` that will skip the snakelization as that would break the format discord expects.
However, when the rest receives the objects already in the snake_case form (eg in a proxy) it will actually fail the check for `nameLocalizations` and `descriptionLocalizations` breaking the format that discord expects resulting in an error on the request
fixes #3666
> fix(rest): ignore snakelized properties in `changeToDiscordFormat`

- packages/bot/src/bot.ts
from #3422:
> - `options.gateway.token` is now also optional since it can be inherited from `options.token`.
While the types have a `Parital` typescript does not actually correctly understand this, and it errors if you don't provide the token in the `rest` and `gateway` nested objects. This pr changes the type to make them actually optional
> fix(bot): Make token in rest and gateway for `createBot` optional

- packages/rest/src/manager.ts
This reverts the recently merged #3795 and changes the approach to check for a `_` instead of the manual check we were doing before.
> fix(rest): Use a `_` check instead of the manual one on the switch

- examples/advanced/src/bot.ts
- examples/beginner/src/bot.ts
- examples/bigbot/src/bot/bot.ts
- examples/minimal/src/bot.ts
- packages/bot/src/bot.ts
- packages/bot/src/transformers.ts
- packages/discordeno/src/bin/config.ts
- packages/discordeno/src/bin/generate/desiredProperty.ts
- packages/discordeno/src/bin/generate/typescript.ts
- packages/types/src/discordeno.ts
1. Fix typo in DesiredProp**rie**tiesBehavior
2. Remove the RecursivePartial<T> from `DiscordenoConfig.desiredProperies.properties` as it makes the object just harder to work with, as it is "lying" since the object should always be constructed with all the props
> [!WARNING]
> This is breaking since it is renaming a type
> fix(discordeno)!: Fix some errors in `DiscordenoConfig`

- packages/rest/src/manager.ts
In #3825 an if was added to ignore all fields that had `_` in the key as they were already in snake_case. However, the check simply ignored the key, but we do not mutate the object, we create another one so all keys with `_` provided to rest are ignored.
> fix(rest): Add the property if it has `_` to the object

- packages/types/src/discordeno.ts
Currently we don't have the `attachments` member to the `CreateMessageOptions`, this PR adds it and changes the type for the exiting `attachments` member in the `EditMessage` interface as Discord in its documentation states:
> For the `attachments` array in Message Create/Edit requests, only the `id` is required.
> fix(types): Add attachments to `CreateMessageOptions`

- packages/bot/src/helpers.ts
- packages/rest/src/manager.ts
- packages/rest/src/routes.ts
- packages/rest/src/types.ts
- packages/rest/src/typings/routes.ts
Add get sticker pack endpoint
- upstream: https://github.com/discord/discord-api-docs/pull/7065
- fixes #3842
> feat(rest,bot): Add get sticker pack endpoint

- packages/bot/src/transformers/application.ts
- packages/bot/src/transformers/reverse/application.ts
- packages/bot/src/transformers/types.ts
- packages/types/src/discord.ts
Add the `approximate_user_install_count` member to `DiscordApplication` and the `approximateUserInstallCount` memebr to `Application`
This pr also adds a few missing values from `Application` that were declared in `DiscordApplication`
> [!NOTE]
> `approximate_user_install_count` was added to the reverse transformers, however a bunch more proprieties are missing from it. However, since some reverse transformers that are needed are missing this pr does not add the missing members. 
- upstream: https://github.com/discord/discord-api-docs/pull/7070
- fixes: #3843
> feat(bot,types): Add `approximate_user_install_count` to `DiscordApplication`

- packages/gateway/src/manager.ts
Currently `gateway.resharding.getSessionInfo` is always present but it will error out when called, this makes it difficult to change the method from `createBot` or to disable resharding in case it is not set (to avoid spamming errors to users)
> feat(gateway): Make `resharding.getSessionInfo` optional

- packages/gateway/src/manager.ts
Currently most if not all the resharding logs are warnings, however the logs for a check if needed when it isn't needed don't need to be warnings
This PR changes some to debug and some others to info as they contain useful information for the user
> fix(gateway): change logLevel for some resharding logs

- packages/rest/src/manager.ts
Some of the methods in the REST manager have a hardcoded object literal with the keys instead of an object as a parameter, this is fine as sometimes we need to adjust the object. However, this creates an issue if the body is in `snake_case` and needs to be edited by `changeToDiscordFormat` since #3825.
This pr changes these objects to use `camelCase` member names so that `changeToDiscordFormat` can do its job
> fix(rest): Use camelCase for body members

- examples/advanced/src/register-commands.ts
- examples/beginner/src/register-commands.ts
- examples/bigbot/src/bot/register-commands.ts
- examples/minimal/src/register-commands.ts
Currently we do not load the commands before registering them to discord, this makes so it always sends an empty array
> fix(examples): Add commands dir import to examples register commands script

- packages/bot/src/helpers.ts
- packages/rest/src/manager.ts
- packages/rest/src/types.ts
Add the Get Guild Role endpoint
- upstream: https://github.com/discord/discord-api-docs/pull/7074
- fixes #3860
> feat(bot, rest): Add get guild role endpoint

- packages/bot/src/transformers.ts
- packages/bot/src/transformers/interaction.ts
- packages/bot/src/transformers/message.ts
- packages/bot/src/transformers/onboarding.ts
Remove the direct calls to transformers in favor of the `bot.transformers` object and support for customizers
> [!WARNING]
> This is breaking, because `transformInteractionDataResolved` did not use the ""standard"" way to make a transformer and used 3 parameters, this has been changed to be 2 parameters the second one being an object however this is a breaking change
> fix(bot)!: Remove direct calls to transformers

- packages/gateway/src/Shard.ts
- packages/gateway/src/manager.ts
Currently the only way to make a shard have a presence is editing it after the shard is connected, however the `DiscordenoShard` class has a `makePresence` that unless it is used manually it cannot be used as the `GatewayManager` does not accept this method.
This pr adds the `makePresence` method to the `GatewayManager` and passes it down when creating a shard
> feat(gateway): Expose `makePresence` from `GatewayManager`

- packages/types/src/shared.ts
Add `PollResult` (46) message type and `poll_result` embed type.
This does not include the typings for `poll_result` embeds fields.
- Upstream: https://github.com/discord/discord-api-docs/pull/7050
> feat(types): Add `poll_result` Message/Embed Type

- packages/types/src/discordeno.ts
Set `recurrenceRule` as nullable in update guild scheduled event.
- upstream: https://github.com/discord/discord-api-docs/pull/7062 
> [!WARNING]
> This is breaking as the original pr used `snake_case` for `recurrence_rule` in update and create of guild scheduled event. This causes issues of consistency and (potentially) runtime errors such as the ones fixed in #3849
> fix(types)!: Set `recurrenceRule` as nullable in update guild scheduled event

- packages/rest/tests/constants.ts
- packages/utils/src/token.ts
This replaces the usage of `Buffer` from `node:buffer` with `atob` for `getBotIdFromToken`.
While node calls it "legacy" (stability 3 in the docs) and suggests using `Buffer`, using `atob` has the following advantages:
- It does not make [Vite](https://vitejs.dev) error at build time (`@discordeno/utils` does not have a reason to not being able to be used in a web page, for example the `createOAuth2Link` can be used)
- It throws on invalid characters. This uncovered that the REST unit tests used a token with invalid UTF characters
> fix(utils): Use `atob` instead of `node:buffer` for `getBotIdFromToken`

- packages/bot/src/transformers/auditLogEntry.ts
- packages/bot/src/transformers/reverse/auditLogEntry.ts
- packages/bot/src/transformers/types.ts
- packages/types/src/discord.ts
Our current `DiscordAuditLogChange` is pretty much outdated, on both the `types` and `bot` package. This is because while discord has been adding properties, we haven't updated the audit log change to reflect those, as it is very easy to forget about it.
This PR removes completely the `AuditLogChange` type and refactors the `DiscordAuditLogChange` to use the actual objects as source for all the values + some manually done for handling the exceptions discord has for some objects. The reason why I chose this is the following note in the Discord Developer Docs:
> You should assume that your app may run into any field for the changed object, though none are guaranteed to be present. In most cases only a subset of the object's fields will be in the changes array.
So, while discord may never …
> fix(bot,types)!: update `DiscordAuditLogChange` to be less manual

- packages/types/src/discord.ts
- packages/types/src/discordeno.ts
Action-Row are not always at the top-level of a components tree, however they still can't be nested so the types has been adjusted to match this behavior
- Upstream: https://github.com/discord/discord-api-docs/pull/7115
> [!WARNING]
> This is a breaking change due to some members in `DiscordSelectMenuComponent` having an incorrect name.
> [!NOTE]
> Some values on `DiscordSelectMenuComponent` were missing and got added
> feat(types)!: Action rows are not always the top-level

- packages/types/src/discordeno.ts
Add the poll object to `InteractionCallbackData`, this allows for both sending a poll and edit it in a response
- Upstream: https://github.com/discord/discord-api-docs/pull/7090
> feat(types): Add the poll object to `InteractionCallbackData`

- packages/bot/src/transformers/message.ts
Always include the message content even if it is undefined or null. This avoids issues when the content is a falsy value (according to javascript).
fixes #3964
> fix(bot): Always include the message content if desired

- packages/bot/src/transformers.ts
- packages/bot/src/transformers/message.ts
- packages/bot/src/transformers/types.ts
- packages/types/src/discord.ts
Add command target to interaction response messages
- Upstream: https://github.com/discord/discord-api-docs/pull/7181
> feat(types,bot): Add command target to interaction response messages

- packages/types/src/discord.ts
The `serialized_source_guild` in a template uses numbers and not strings, so we need to change the types in `DiscordTemplateSerializedSourceGuild`
- Upstream: https://github.com/discord/discord-api-docs/pull/7232
> feat(types): Use numbers in the template partial source guild

- packages/rest/src/types.ts
Fix the remark on `getWebhook`
- upstream: https://github.com/discord/discord-api-docs/pull/7229
> fix(rest): Fix the remark on `getWebhook`

- packages/bot/src/transformers/channel.ts
- packages/bot/src/transformers/guild.ts
- packages/bot/src/transformers/interaction.ts
- packages/bot/src/transformers/member.ts
- packages/bot/src/transformers/message.ts
- packages/bot/src/transformers/role.ts
- packages/bot/src/transformers/types.ts
- packages/bot/src/transformers/user.ts
This also changes the way we type our base structures, as using `as` was suppressing errors such as the one fixed in this PR
> fix(bot): Incorrect return type in `interaction.respond`

- .github/workflows/release.yml
- package.json
- packages/benchmarks/package.json
- packages/bot/package.json
- packages/discordeno/package.json
- packages/gateway/package.json
- packages/rest/package.json
- packages/rest/src/manager.ts
- packages/types/package.json
- packages/utils/package.json
- yarn.lock
This bumps the version of all packages to 19.0.0 and also configures the CI release to use `next` tag for commit releases and `latest` if a release has been published
The `next` tag was used because we use `.next-` in the semver suffix for our commit releases
> [!NOTE]
> This also enables NPM release provenance (https://docs.npmjs.com/cli/v10/commands/npm-publish#provenance)
> ci: Release v19

- .github/workflows/release.yml
The turbo cache in the release workflow seems to be doing more damage than good.
In the normal commits we do it isn't useful anyway since it runs before there is anything cached and on a release, it seems to omit stuff (for example the v19.0.0 release does not have the CJS build for whatever reason, and the main suspect is the turbo cache)
> ci: Remove turbo cache from release

- packages/bot/src/transformers/emoji.ts
- packages/bot/src/transformers/guild.ts
- packages/bot/src/transformers/interaction.ts
- packages/bot/src/transformers/member.ts
- packages/bot/src/transformers/message.ts
- packages/bot/src/transformers/role.ts
- packages/bot/src/transformers/user.ts
This PR exports objects like `baseGuild`, `baseRole` etc. so users can import it and use if they need (needed for `dd-cache-proxy` to provide the getters like dd does).
Types for `baseEmoji` is also changed to be consistent with others.
> refactor(bot): export base objects with getters from transformers

- packages/bot/src/transformers/component.ts
Add some missing breaks in the switch in the component transformer that were causing it to return the incorrect set of data most of the times
> fix(bot): Add missing breaks in component transformer switch

- packages/bot/src/commandOptionsParser.ts
- packages/bot/src/desiredProperties.ts
- packages/bot/src/transformers/interaction.ts
Fix the types for `commandOptionsParser`, this also changes the `TransformProperty` to check the nested objects to ensure all objects have the correct desired proprieties applied to them
> fix(bot)!: fix type errors when using `commandOptionsParser`

- packages/rest/src/manager.ts
Currently when you get an error from rest when you're using a rest proxy, the error message will be like this:
```
Error: Error: 404: Not Found
at Object.makeRequest (file:///D:/test/dd-test/node_modules/@discordeno/rest/dist/esm/manager.js:412:43)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.get (file:///D:/test/dd-test/node_modules/@discordeno/rest/dist/esm/manager.js:442:29)
at async Object.getGuild (file:///D:/test/dd-test/node_modules/@discordeno/rest/dist/esm/manager.js:1054:20)
at async Object.getGuild (file:///D:/test/dd-test/node_modules/@discordeno/bot/dist/esm/helpers.js:292:34)
```
But when you get an error while you don't use a rest proxy, the error message will be like this:
```
Error: Failed to send request to discord.
at …
```
> fix(rest): errors returned from makeRequest() doesn't provide more info rest is proxied

- packages/gateway/src/Shard.ts
- packages/gateway/src/manager.ts
- packages/gateway/tests/integration/connection.spec.ts
Currently, calling `shard.resume()` closes old socket (which calls `handleClose()`) and creates a new one and updates `this.socket`. However, resume doesn't wait for the old socket to be closed, so it creates new socket and connects, and then `handleClose()` is being called. This function sets `this.socket` to `undefined`, causing new socket object to be gone, which prevents us from sending heartbeat on the new socket, which causes Discord to send `1000` close close, which makes us try to resume again and this is stuck on a loop (and sometimes stuck on identify loop, causing token to be reset).
This PR fixes that issue by having a function that will be called inside `handleClose` so `resume` can wait until the function is called
> fix(gateway): shard.resume() ending in a loop of constant resumes

- packages/bot/src/commandOptionsParser.ts
- packages/bot/src/desiredProperties.ts
This removes the `WithAtLeast` type helper and replaces its usage with `& { ... }` as they seem to do the same thing.
> fix!: Remove `WithAtLeast`

- packages/rest/src/manager.ts
We used `file<n>` instead of `files[<n>]`, while this still works it makes stuff that relies on the file index fail, for example `attachments` when used will error about it being unable to find the file data that the id refers to
> fix(rest): Use files[n] for uploading files

- packages/bot/src/transformers/types.ts
- packages/types/src/discord.ts
Entitlements dates are nullable and not optional as discord always sends them but with null in some cases
- Upstream: https://github.com/discord/discord-api-docs/pull/7288
> [!WARNING]
> This is breaking as changing a `?: ` (optional) to nullable (`| null`) will cause some type errors if you are using the member
> fix(types,bot)!: Dates are nullable not optional in Entitilement

- packages/gateway/src/Shard.ts
In some case, such as when running in Bun, the `WebSocket.onclose` event handler is fired before we can actually set the `resolveAfterClose` to know that the `WebSocket` and the underlying TCP resources are dropped, so the code never resolved and gets stuck waiting forever
> fix(gateway): close not resolving in some cases

- packages/bot/src/transformers/interaction.ts
Allow `ModalSubmit` interactions to be responded to by the `interaction.edit()` function and `interaction.deferEdit()`. Previously, these functions only allowed `MessageComponent` interactions, however modal interactions work as well.
Previously, this was only possible with `bot.helpers.sendInteractionResponse()` with type `InteractionResponseTypes.UpdateMessage`
> Allow edit and deferEdit on modal submit interaction

- denoImportMap.json
- packages/gateway/src/manager.ts
Currently `gateway.requestMembers()` returns an empty array if the user doesn't provide a nonce or the `gateway.cache.requestMembers.enabled` is enabled, this gives users the pain of generating their own nonce if they want members to be returned by this function, which could result in bad implementation so this PR makes it generate a nonce by itself so user doesn't have to and could just use `gateway.requestMembers(guildId)`.
This PR also updates the docs comment for `requestMembers` to clarify about the need for `gateway.cache.requestMembers.enabled` to be set if the user wishes to receive members in return value.
> fix(gateway): set a nonce if none is provided for gateway.requestMembers

- examples/bigbot/package.json
- examples/bigbot/yarn.lock
Ran into this being missing early, seems to be included in the other examples just not the big bot one.
> fix(bigbot-example): add missing dotenv dependency

- examples/bigbot/src/config.ts
MESSAGEQUEUE_ENABLE wasnt an actual boolean so rabbitmq was always required unless removed.
> fix(bitbot-example): MESSAGEQUEUE_ENABLE being a string instead of a bool

- examples/bigbot/package.json
- examples/bigbot/yarn.lock
Adds the chokidar package thats required for the --watch option used by the build:watch command.
> fix: add chokidar as dev dependencie 

- packages/utils/src/builders/embeds.ts
Fixes a small typo in the EmbedsBuilder tsdoc, @itohatweb requsted to make a seperate pr for this in #4077
> fix: EmbedsBuilder missing s typo

- packages/utils/src/builders/embeds.ts
Uses a fallback value if nothing is passed because the timestamp property is marked as optional. This prevents errors when using the function without arguments. If needed I can add a comment to the jsdoc to explain that this is what happends when nothing is being passed into the function since the "default" changed now.
> fix(utils): set Date.now() as timestamp if none is provided in EmbedsBuilder.setTimestamp()

- packages/bot/src/bot.ts
- packages/bot/tests/e2e/resetguilds.spec.ts
- packages/gateway/package.json
- packages/gateway/tests/integration/connection.spec.ts
- packages/gateway/tests/integration/websocket.ts
- yarn.lock
Bot E2E:
- The test for some reason specified a custom gateway message handler that did not work because it tried to use incorrectly the events object
Gateway Integration:
- uWS.JS is a napi npm module, this means that to run the integration tests we needed a version of node that is compatible with the uWS version we install, however this can get annoying & running the latest node version can sometime not work
- uWS.JS did not like 3xxx close codes and refused to send them back to the shard causing issues
- In the project we install `ws` anyway that provides a `WebSocketServer` so we can use that instead of uWS, both supports getting a random port from the OS
- Now the test shouldn't take 1m+ to exit due to the shard ratelimit bucket needing to refill, as we clear the timeout in the test
> test(bot,gateway): Fix Bot E2E and Gateway Integration tests

- packages/bot/src/helpers.ts
rest already supports `botBannerURL` but typings in bot doesn't have it so you can't pass the option without having ts error, this pr fixes that
> fix(bot): add botBannerURL option to helpers.editBotProfile()

- packages/rest/src/manager.ts
Currently we always do `.text()` on the rest proxy response body, however when the server gives us json (or at least claims it does) we can parse it as JSON and use that in the error cause
> feat(rest)!: Parse json body when possibile in rest proxy

- packages/bot/src/commandOptionsParser.ts
Currently the `InteractionResolvedUser`, `InteractionResolvedChannel` and `InteractionResolvedMember` used the complete `User`, `Channel`, `Member` without any desired properties and relied on the user to apply them, which is not really feasible even when using `TransformProperty` like we were doing, as that will need to have the entire object to work
> [!NOTE]
> The old types still exist, new types named `InteractionResolvedDataXYZ` now use desired properties directly, however they are marked as deprecated
> fix(bot): Use desired properties in InteractionResolvedXYZ

- packages/gateway/src/Shard.ts
- packages/types/src/shared.ts
According to Discord developers portal documentation page, [initializing a disconnect](https://discord.com/developers/docs/events/gateway#initiating-a-disconnect) section suggests that close codes `1000` (`GatewayCloseEventCodes.NormalClosure`) and `1001` will invalidate bot and bot will appear offline. By taking a look at how shutting down process works in `discordeno`, it seemed like the library is lacking the ability to fully shutdown with the bot appearing offline.
Therefore, I experimented with closing gateway manually by providing the close codes `1000` and `1001`. The code `1001` is not allowed by `discordeno`, which is fine. However, the code `1000` triggers session resume, which I assumed a bug.
I kindly ask to review my pull request and consider the little change I've added. …
> fix(shutdown): prevent resume when closed with `GatewayCloseEventCodes.NormalClosure`.

- website/docs/desired-properties.md
If we specify the generic other generics stop being inferred so if we specify the desired properties behavior to ChangeType it type errors as TS still thinks that it should be RemoveKey
> docs: Use as instead of specifying the generic

- packages/types/src/discordeno.ts
`auto_archive_duration` is an optional param, see:
https://discord.com/developers/docs/resources/channel#start-thread-from-message-json-params
https://discord.com/developers/docs/resources/channel#start-thread-without-message-json-params
https://discord.com/developers/docs/resources/channel#start-thread-in-forum-or-media-channel-jsonform-params
> fix: thread create autoArchiveDuration being a required param

- packages/bot/src/helpers.ts
- packages/bot/src/transformers.ts
- packages/bot/src/transformers/threadMember.ts
- packages/bot/src/transformers/types.ts
- packages/rest/src/manager.ts
- packages/rest/src/routes.ts
- packages/rest/src/types.ts
- packages/rest/src/typings/routes.ts
- packages/types/src/discord/channel.ts
- packages/types/src/discordeno.ts
This is a breaking change because `Member.guildId` is now marked optional, as there are some places where it's impossible to get guild id of the thread member
> feat!: add missing params to getThreadMember() and getThreadMembers()

- packages/bot/src/transformers/types.ts
Discordeno was using `Record<Locales, string>` for some `nameLocalizations` and `descriptionLocalizations` properties, causing a type error.
This pull request changes the type `Record<Locales, string>` to `Localization` (which it is `Partial<Record<Locales, string>>`)
> fix(types): use `Localization` instead of `Record<Locales, string>`

- packages/types/src/discordeno.ts
This pull request includes a small change to the `ButtonComponent` interface in the `discordeno.ts` file. The change adds a new property to support premium-style buttons.
* [`packages/types/src/discordeno.ts`](diffhunk://#diff-e25808c8da925da054561fc5fc6a56358d75ecb11c90d8d0d8b0596c88aed095R151-R152): Added `skuId` property to the `ButtonComponent` interface to identify purchasable SKUs for premium-style buttons.
> fix(types): Add missing skuId property in ButtonComponent

- packages/rest/src/manager.ts
These endpoints don't require auth, source from community maintained docs:
- [deleteWebhookMessage](https://docs.discord.sex/resources/webhook#delete-webhook-message)
- [editOriginalInteractionResponse](https://docs.discord.sex/interactions/receiving-and-responding#edit-original-interaction-response)
> fix(rest): deleteWebhookMessage() and editOriginalInteractionResponse() doesn't require auth

- packages/bot/src/helpers.ts
- packages/rest/src/types.ts
While discord does not say anything explicit about deprecating the `createGuildFromTemplate` endpoint, it is a fair assumption to make that it is included in this change
- upstream: https://github.com/discord/discord-api-docs/pull/7469
> feat(bot,rest): Deprecate `createGuild` and `createGuildFromTemplate`

- packages/bot/src/utils.ts
The other two functions use BigString so why not snowflakeToTimestamp?
> Improve consistency for snowflakeToTimestamp

- packages/gateway/src/Shard.ts
Since we already have a debug log that logs close code with reason in `shard.handleClose()` and another log for `shard.resume()`, this one is redundant.
Moreover, something has changed on Discord/CloudFlare/Hetzner's side around 2 months ago and since then, the number of shard closures has increased with close code `1006` and this log is spamming the console (yes I have verified it's not my code or just my server but is something that people using other libraries are also experiencing).
> refactor: don't log about resuming in shard.handleClose

- packages/types/src/discord/components.ts
- packages/types/src/discordeno.ts
The limit is still in place however it is 40 total now, so it is a bit more complicated to explain and the discord docs are better at doing so than what we can do with JSDoc
- Upstream: https://github.com/discord/discord-api-docs/pull/7534
> fix(types): Remove comment limit on number of components

- packages/gateway/src/Shard.ts
- packages/gateway/src/manager.ts
remove `shardIsReady`, wait for the `.identify()` promise to resolve instead
> fix!: Remove shardIsReady

- packages/types/src/discordeno.ts
`messageReference.failIfNotExists` is optional as per docs https://discord.com/developers/docs/resources/message#message-reference-structure
> fix: CreateMessageOptions.messageReference.failIfNotExists is optional

- packages/utils/src/images.ts
- packages/utils/tests/images.spec.ts
JPG doesn't have support for transparent backgrounds and Discord uses WEBP by default within the client as well so it's better to just default to WEBP instead of JPG in `formatImageUrl()`
> refactor: set default format to webp instead of jpg in formatImageUrl()

- packages/bot/src/desiredProperties.ts
- website/docs/desired-properties.md
Using an object allows typescript to error in more cases as with strings
if the original propriety was a string it would not error for stuff like
`.endsWith(...)`
We use a symbol to make sure the type doesn't actually become a generic
object, but instead is a specific type that can be checked against.
> fix(bot): Use an object to present desired properties errors

- packages/bot/src/desiredProperties.ts
- packages/bot/src/helpers.ts
- packages/bot/src/transformers.ts
- packages/bot/src/transformers/message.ts
- packages/bot/src/transformers/types.ts
- packages/rest/src/manager.ts
- packages/rest/src/routes.ts
- packages/rest/src/types.ts
- packages/rest/src/typings/routes.ts
- packages/types/src/discord/message.ts
- packages/types/src/discordeno.ts
- upstream: https://github.com/discord/discord-api-docs/pull/7640
- upstream: https://github.com/discord/discord-api-docs/pull/7585
- upstream: https://github.com/discord/discord-api-docs/pull/7630
> [!NOTE]
> This does change the endpoint `pinMessage` and `unpinMessage` use, however they do seem to have the exact same behavior
> feat(types,rest,bot): Updated message pin endpoints

- packages/rest/tests/e2e/automod.spec.ts
- packages/rest/tests/e2e/emoji.spec.ts
- packages/rest/tests/e2e/guild.spec.ts
- packages/rest/tests/e2e/member.spec.ts
- packages/rest/tests/e2e/message.spec.ts
- packages/rest/tests/e2e/misc.spec.ts
- packages/rest/tests/e2e/role.spec.ts
- packages/rest/tests/e2e/stickers.spec.ts
- packages/rest/tests/e2e/user.spec.ts
- packages/rest/tests/e2e/utils.ts
- packages/rest/tests/e2e/webhook.spec.ts
Discord has deprecated and now disabled bot from using the createGuild endpoint, we used it heavly for our tests, for now we disable these test (38 tests) however we should find another way to do these tests
> fix(e2e): Fix broken e2e (by removing tests)

- packages/types/src/discord/auditLog.ts
* upstream: https://github.com/discord/discord-api-docs/pull/7706
> api-docs: Document automod quarantine audit log action type

- packages/bot/src/transformers/interaction.ts
If we ACK the interaction and the request is not successful and then the user tries to use the helpers again they will almost always get an error about unknown webhooks or unknown interactions
test code:
```ts
bot.events.interactionCreate = async (interaction) => {
try {
await interaction.respond({ components: [{ type: MessageComponentTypes.TextDisplay, content: 'Hello World!' }] })
} catch (error) {
await interaction.respond({ content: 'An error occurred while processing your request.\nDetails: ```ts\n' + inspect(error) + '```' })
}
}
```
> fix(bot): ACK the interaction only after a successful response

- packages/bot/src/events.ts
- packages/bot/src/handlers/guilds/GUILD_DELETE.ts
It is now merged with the guildDelete event
> feat(bot)!: Remove bot.events.guildUnavailable

- packages/benchmarks/src/benchmarks/memory.ts
- packages/benchmarks/src/benchmarks/transformers.ts
- packages/bot/src/bot.ts
- packages/bot/tests/e2e/resetguilds.spec.ts
Allowing desired properties to be omitted makes it harder to get started with discordeno as you won't know you need them unless you read the docs
> feat(bot)!: Make desiredProperties required

- packages/gateway/src/Shard.ts
- packages/gateway/src/types.ts
Currently we rely on `fzstd` for the zstd-stream support, node also added support for this in v22.15 and v23.8
https://nodejs.org/docs/latest/api/zlib.html#class-zlibzstddecompress
The docs do mark this as "Experimental" however fzstd is also at it's 0.1 version, and by my testing node:zlib zstd works fine
> feat(gateway): Use `node:zlib` zstd when available

- .github/workflows/lib-check.yml
The change was done in https://github.com/discordeno/discordeno/pull/4319 but during the main branch merge(s) it got lost due to conflicts (?)
So this pr actually makes lib-check use `biome ci`
> ci: Use `biome ci` in lib-check format

- packages/bot/src/transformers.ts
- packages/bot/src/transformers/interaction.ts
- packages/bot/src/transformers/threadMember.ts
This allows us to ensure that customizers always follow the correct types for the transformers and we don't have 2 places to add the types.
> [!NOTE]
> This _tecnically_ is a breaking change due to following mistakes in the old customizers/transformers:
> - `guildOnboardingPromptOption` transformer did actually support desired properties
> - `incidentsData` transformer did actually support desired properties
> - `inviteStageInstance` transformer extra did not had the guildId as optional
> - `interactionDataResolved` customizer did not used `TransformProperty` like the transformer does
> - `threadMember` customizer extra used `BigString` however all other customizer use `bigint`
>
> Also, to avoid other breaking changes beside the ones listed above I used the following code:
> ```ts
> type …
```
> refactor(transformers)!: Use type helper to define customizers

- packages/types/src/discord/message.ts
It's referred to as IS_COMPONENTS_V2 in docs so we should keep it plural as well
> chore(types)!: rename MessageFlags.IsComponentV2 to IsComponentsV2 to match docs

- packages/types/src/discord/interactions.ts
- upstream: https://github.com/discord/discord-api-docs/pull/7458
- fixes #4507
> fix(types): Fix bounds for ApplicationCommandOptionTypes.Integer
